// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AbortReason =
  | "ForeignPledgeInputConflict"
  | "LockInputsFailed"
  | "LockOutputsFailed"
  | "LockInputsOutputsFailed"
  | "ExecutionFailure"
  | "OneOrMoreInputsNotFound"
  | "InsufficientFeesPaid"
  | "FeePaymentInMainIntent"
  | "EpochExpired";
