// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PedersenCommitmentBytes } from "./PedersenCommitmentBytes";
import type { SchnorrSignatureBytes } from "./SchnorrSignatureBytes";

export type AbridgedTransactionKernel = {
  version: number;
  fee: bigint;
  lock_height: bigint;
  excess: PedersenCommitmentBytes;
  excess_sig: SchnorrSignatureBytes;
};
