// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RestrictedAccessRule } from "./RestrictedAccessRule";

/**
 * Represents the types of possible access control rules over a component method or resource
 */
export type AccessRule = "AllowAll" | "DenyAll" | { Restricted: RestrictedAccessRule };
