// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";

export type AccountWithPublicKey = { account: Account; owner_public_key: RistrettoPublicKeyBytes };
