// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddress } from "./ComponentAddress";

export type Account = {
  name: string | null;
  address: ComponentAddress;
  key_index: number;
  is_confirmed_on_chain: boolean;
  is_default: boolean;
};
