// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddress } from "./ComponentAddress";
import type { Epoch } from "./Epoch";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";
import type { KeyId } from "./wallet-types/KeyId";

export type Account = {
  name: string | null;
  component_address: ComponentAddress;
  view_only_key_id: KeyId;
  owner_key_id: KeyId | null;
  owner_public_key: RistrettoPublicKeyBytes;
  birthday_epoch: Epoch;
  is_confirmed_on_chain: boolean;
  is_default: boolean;
};
