// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Possible allocatable address types
 */
export type AllocatableAddressType = "Component" | "Resource";
