// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A 128-bit signed amount.
 *
 * This is a general purpose signed integer, but is primarily used to represent the smallest unit of value in
 * resources/vaults etc.
 *
 * This allows Tari to support a massive number tokens within resources.
 * e.g. 2 ETH = 2 x 10^18 Gwei.
 */
export type Amount = string | number | bigint;
