// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { CheckOrd } from "./CheckOrd";
import type { NftCheck } from "./NftCheck";
import type { NonFungibleId } from "./NonFungibleId";
import type { ResourceAddress } from "./ResourceAddress";

export type Assertion = { "BktAmt": { resource_address: ResourceAddress, is: CheckOrd, amount: Amount, } } | "NtNil" | { "BktCtnNft": { resource_address: ResourceAddress, check: NftCheck, nfts: Array<NonFungibleId>, } };
