// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessRule } from "./AccessRule";
import type { BuiltinPredicate } from "./BuiltinPredicate";
import type { Covenant } from "./Covenant";
import type { TemplateFunction } from "./TemplateFunction";

/**
 * One conjunct of a [`SpendCondition`] leaf. Atoms are not self-referential — composition lives in the enclosing
 * conjunction (AND) and the condition tree (OR), never inside an atom — so the type carries no recursion to bound.
 */
export type AtomicCondition =
  | { AccessRule: AccessRule }
  | { TemplateFunction: TemplateFunction }
  | { Builtin: BuiltinPredicate }
  | { Covenant: Covenant };
