// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Blob } from "./Blob";

/**
 * Ordered collection of `Blob`s carried by a transaction. Index 0 corresponds to the first
 * blob, etc. Instructions and arguments reference blobs by `BlobIndex` into this list.
 */
export type Blobs = Array<Blob>;
