// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An opaque, content-addressed payload referenced from a transaction's instructions by index.
 *
 * Blobs are the prunable side-channel of a transaction: only their per-blob hashes participate
 * in the signing domain, so blob payloads can be dropped post-finalization without affecting
 * signature verifiability or the transaction id.
 *
 * JSON encoding is base64.
 */
export type Blob = string;
