// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Blob } from "./Blob";

/**
 * Ordered collection of blobs carried by a transaction. Index 0 is the first blob, etc.
 * Instructions and arguments reference blobs by `BlobIndex` (number) into this list.
 */
export type Blobs = Array<Blob>;
