// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";

/**
 * A typed collection of per-blob commitments — the prunable surrogate of `Blobs` in the
 * signing domain.
 */
export type BlobHashes = Array<Hash32>;
