// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An opaque, content-addressed payload referenced from a transaction's instructions by index.
 *
 * Blobs are the prunable side-channel of a transaction: the bytes themselves are not bound
 * directly into the signing domain — only their per-blob hashes are. Once a transaction has
 * been finalized and its retention window has elapsed, blob payloads can be discarded without
 * affecting the transaction id or signature verifiability.
 *
 * JSON encoding is base64 (matches `PublishTemplate` binary today). Borsh and CBOR use the
 * `Bytes` byte-array form.
 */
export type Blob = string;
