// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "./Epoch";
import type { ExtraData } from "./ExtraData";
import type { NodeHeight } from "./NodeHeight";
import type { ShardGroup } from "./ShardGroup";

export interface BlockHeader {
  id: string;
  network: string;
  parent: string;
  justify_id: string;
  height: NodeHeight;
  epoch: Epoch;
  shard_group: ShardGroup;
  proposed_by: string;
  total_leader_fee: number;
  state_merkle_root: string;
  command_merkle_root: string;
  signature: { public_nonce: string; signature: string } | null;
  timestamp: number;
  epoch_hash: string;
  extra_data: ExtraData;
}
