// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The ID of a block in the Tari consensus protocol.
 */
export type BlockId = string;
