// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockHeader } from "./BlockHeader";
import type { Command } from "./Command";
import type { ProposalCertificate } from "./ProposalCertificate";
import type { TimeoutCertificate } from "./TimeoutCertificate";

export interface Block {
  header: BlockHeader;
  justify: ProposalCertificate;
  commands: Array<Command>;
  timeout_certificate: TimeoutCertificate | null;
  justify_qc_id: string | null;
  commit_qc_id: string | null;
  block_time: number | null;
  stored_at: string | null;
}
