// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bucket identifier. This identifier is assigned at runtime.
 */
export type BucketId = number;
