// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";
import type { HashAlg } from "./HashAlg";

/**
 * A native, consensus-fixed spend predicate committed as a [`SpendCondition::Builtin`] leaf (TIP-0006).
 *
 * Unlike a [`TemplateFunction`], a builtin requires no deployed template and is evaluated natively by the engine —
 * the canonical semantics live in trusted core code, so the set is append-only and a shipped variant is never
 * resemanticised. Each variant is a pure boolean predicate over the spending transfer; rejecting a spend leaves its
 * inputs unspent. A predicate that needs spender-supplied data reads the witness `data` blob
 * ([`SpendWitness::ScriptPath`](super::SpendWitness::ScriptPath)) as its complete raw input — see
 * [`BuiltinPredicate::consumes_data`] and the sole-consumer rule it implies.
 */
export type BuiltinPredicate =
  | { AfterEpoch: bigint }
  | { BeforeEpoch: bigint }
  | "OutputPreservesCondition"
  | { OutputTo: { condition_root: Hash32; min_value: bigint } }
  | { BalancePreserved: bigint }
  | { HashLock: { hash: Hash32; alg: HashAlg } };
