// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";
import type { HashAlg } from "./HashAlg";

/**
 * A native, consensus-fixed spend predicate committed as a `SpendCondition::Builtin` leaf (TIP-0006).
 */
export type BuiltinPredicate =
  | { AfterEpoch: bigint }
  | { BeforeEpoch: bigint }
  | "OutputPreservesCondition"
  | { OutputTo: { condition_root: Hash32; min_value: bigint } }
  | "BalancePreserved"
  | { BalancePreservedWithAllowance: bigint }
  | { HashLock: { hash: Hash32; alg: HashAlg } };
