// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BurnRateChange } from "./BurnRateChange";

export type BurnRateGovernanceState = { schedule: Array<BurnRateChange>; retired_from: number | null };
