// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A wrapper around `Vec<u8>` that serializes to and from bytes efficiently.
 * Unfortunately, due to some factors (impl serde for Vec<T>, no specialization) ciborium will represent bytes as
 * `Array(vec![Integer(u8), ....])` instead of `Bytes(vec![u8, ...])`. which results in a significant bloat in size.
 * This wrapper uses of the `Bytes` variant in ciborium (similar to `serde_as(as = "Bytes")`).
 */
export type Bytes = string;
