// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A wrapper around a byte buffer that encodes as CBOR major type 2 (Bytes).
 *
 * Without this wrapper, deriving `Encode`/`Decode` on a `Vec<u8>` field would serialise as
 * `Array(Integer(u8), ...)`, which is much larger than the dedicated `Bytes` representation.
 */
export type Bytes = Uint8Array;
