// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JrpcPermissions } from "./JrpcPermissions";

export type Claims = { permissions: JrpcPermissions; exp: bigint; api_key_id?: number | null };
