// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permissions } from "./Permissions";

export type Claims = {
  permissions: Permissions;
  exp: bigint;
  /**
   * Set on a token minted by `webrtc.start` for a connected peer. A
   * delegated token acts with its permissions on the peer's behalf but
   * never counts as the wallet's own interactive session.
   */
  delegated: boolean;
};
