// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The global identifier of a claimed layer-one output in the Tari network.
 * This substate is created when a L1 UTXO is claimed to prevent double claims.
 */
export type ClaimedOutputTombstoneAddress = string;
