// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PedersenCommitmentBytes } from "./PedersenCommitmentBytes";
import type { Scalar32Bytes } from "./Scalar32Bytes";

export type CommitmentSignatureBytes = { public_nonce: PedersenCommitmentBytes; u: Scalar32Bytes; v: Scalar32Bytes };
