// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VotePower } from "./VotePower";

export interface CommitteeMember<TAddr> {
  address: TAddr;
  public_key: string;
  vote_power: VotePower;
}
