// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "./Epoch";
import type { NumPreshards } from "./NumPreshards";
import type { ShardGroup } from "./ShardGroup";
import type { VotePower } from "./VotePower";

/**
 * Represents a "slice" of the 256-bit shard space
 */
export type CommitteeInfo = {
  num_shards: NumPreshards;
  num_shard_group_members: number;
  num_committees: number;
  shard_group: ShardGroup;
  epoch: Epoch;
  total_power: VotePower;
};
