// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { ValueKnowledgeProof } from "./ValueKnowledgeProof";

/**
 * Proof of knowledge of the opening to a commitment and that the commitment commits to a specific value.
 *
 * Used wherever a resource's total supply must account for a value that is otherwise hidden in a commitment:
 * burning a stealth UTXO, and minting a confidential commitment.
 */
export type CommitmentValueProof = {
  /**
   * The claimed value to prove
   */
  value: Amount;
  knowledge_proof: ValueKnowledgeProof;
};
