// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitteeMember } from "./CommitteeMember";

export interface Committee<TAddr> {
  members: Array<CommitteeMember<TAddr>>;
}
