// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentBody } from "./ComponentBody";
import type { ComponentHeader } from "./ComponentHeader";

export type Component = { header: ComponentHeader; body: ComponentBody };
