// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessRule } from "./AccessRule";

/**
 * Information needed to specify access rules to methods of a component
 */
export type ComponentAccessRules = { method_access: Record<string, AccessRule>, default: AccessRule, };
