// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CompressedElgamalVerifiableBalance { encrypted: string, public_nonce: string, }