// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddress } from "./ComponentAddress";

/**
 * A reference to a component, either by its address or by a workspace ID.
 */
export type ComponentReference = { "Address": ComponentAddress } | { "Workspace": number };
