// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddress } from "./ComponentAddress";

export type ComponentCall = { Address: ComponentAddress } | { Workspace: number };
