// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ViewableBalanceProof } from "./ViewableBalanceProof";

/**
 * A zero-knowledge proof that a confidential resource amount is valid
 */
export type ConfidentialStatement = {
  commitment: Array<number>;
  /**
   * Public nonce (R) that was used to generate the commitment mask
   */
  sender_public_nonce: Array<number>;
  /**
   * Encrypted mask and value for the recipient.
   */
  encrypted_data: Array<number>;
  minimum_value_promise: number;
  /**
   * If the view key is enabled for a given resource, this proof MUST be provided, otherwise it MUST NOT.
   */
  viewable_balance_proof: ViewableBalanceProof | null;
};
