// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputBody } from "./OutputBody";

/**
 * A confidential output stored as its own substate, referenced by a vault's commitment list.
 *
 * Spend authorization is entirely controlled by the owning vault's access rules (unlike a stealth
 * [`crate::utxo::Utxo`], which carries its own spend authorization), so no per-output spend key is held here.
 * Spending or burning downs this substate; the only in-place mutation is freezing.
 */
export type ConfidentialOutput = { output: OutputBody; is_frozen: boolean };
