// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { ConfidentialOutputStatement } from "./ConfidentialOutputStatement";
import type { PedersenCommitmentBytes } from "./PedersenCommitmentBytes";

export interface ConfidentialWithdrawProof {
  inputs: Array<PedersenCommitmentBytes>;
  input_revealed_amount: Amount;
  output_proof: ConfidentialOutputStatement;
  balance_proof: { public_nonce: string; signature: string };
}
