// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfidentialOutputAddressContents } from "./ConfidentialOutputAddressContents";

/**
 * Address of a confidential output substate: a resource-namespaced Pedersen commitment.
 *
 * The commitment is the identity, giving network-wide uniqueness (via the duplicate-substate guard).
 * The owning vault is not encoded here — membership in a vault's commitment list is what expresses
 * ownership.
 */
export type ConfidentialOutputAddress = ConfidentialOutputAddressContents;
