// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitmentSignatureBytes } from "./CommitmentSignatureBytes";
import type { ConfidentialWithdrawProof } from "./ConfidentialWithdrawProof";
import type { RangeProofBytes } from "./RangeProofBytes";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";
import type { UnclaimedConfidentialOutputAddress } from "./UnclaimedConfidentialOutputAddress";

export type ConfidentialClaim = {
  public_key: RistrettoPublicKeyBytes;
  output_address: UnclaimedConfidentialOutputAddress;
  range_proof: RangeProofBytes;
  proof_of_knowledge: CommitmentSignatureBytes;
  withdraw_proof: ConfidentialWithdrawProof | null;
};
