// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { SchnorrSignatureBytes } from "./SchnorrSignatureBytes";

/**
 * A covenant sub-balance proof (TIP-0006 `AssertCovenantBalanced`) covering one partition of the transfer: the inputs
 * and outputs that share a `SpendCondition::Script`. It proves the partition's committed value is conserved into
 * outputs carrying that condition save for an exact cleartext `revealed_amount`, without exposing confidential values.
 *
 * A claim is keyed by `partition_input_index` rather than by restating its (potentially large) spend condition; the
 * engine matches it to its partition by that index. The condition is bound into `signature`, so a claim cannot be
 * validated against the wrong partition.
 */
export type CovenantBalanceClaim = {
  /**
   * The index, within the transfer's spent inputs, of the first input belonging to this partition. Identifies the
   * partition without restating its spend condition.
   */
  partition_input_index: number;
  /**
   * The exact net cleartext amount leaving the partition (zero for full conservation). Must be non-negative.
   */
  revealed_amount: Amount;
  /**
   * Schnorr proof of knowledge of the partition's aggregate mask difference.
   */
  signature: SchnorrSignatureBytes;
};
