// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";

/**
 * A native, consensus-fixed covenant committed as a [`SpendCondition::Covenant`] leaf (TIP-0006). Where a
 * [`BuiltinPredicate`] gates an input on a local fact, a covenant constrains the *spending transaction* — which
 * outputs the spent value may flow to, and that the value is conserved — so it propagates conditions forward. Each
 * variant introspects the transfer's outputs natively, with canonical semantics in trusted core code. The set is a
 * curated standard library of common value-routing constraints; anything bespoke is a [`TemplateFunction`] instead.
 */
export type Covenant =
  | "OutputPreservesCondition"
  | { OutputTo: { condition_root: Hash32; min_value: bigint } }
  | { BalancePreserved: bigint };
