// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";
import type { PedersenCommitmentBytes } from "./PedersenCommitmentBytes";

/**
 * Identifies the input whose spend condition is currently executing, including the `condition_root` committed by the
 * UTXO being spent (so a covenant predicate can require outputs to preserve it).
 */
export type CurrentInputView = {
  index: number;
  commitment: PedersenCommitmentBytes;
  condition_root: Hash32 | null;
};
