// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PedersenCommitmentBytes } from "./PedersenCommitmentBytes";

/**
 * Identifies the input whose spend condition is currently executing.
 */
export type CurrentInputView = { index: number; commitment: PedersenCommitmentBytes };
