// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticLevel } from "./DiagnosticLevel";

export type DiagnosticEventFilter = {
  min_level: DiagnosticLevel | null;
  topic_prefix: string | null;
  since: number | null;
  until: number | null;
};
