// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticLevel } from "./DiagnosticLevel";

export type DiagnosticEventRecord = {
  id: number;
  timestamp: number;
  level: DiagnosticLevel;
  topic: string;
  message: string;
  fields: { [key in string]?: string };
};
