// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Used by the receiver to determine the value component of the commitment, in both confidential transfers and Minotari
 * burns
 */
export type EncryptedData = string;
