// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Used by the receiver to determine the value and mask of the commitment. Used in stealth and confidential transfers,
 * as well as Minotari burns
 */
export type EncryptedData = string;
