// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The atom committed by an [`Command::EndEpoch`] command.
 *
 * Carries the base-layer boundary-block hash of the *next* epoch. Because the hash is part of the
 * command, it is committed in the block's command merkle root and ratified by the quorum that
 * commits the end-of-epoch block: a validator only votes for the EOE block if `next_epoch_hash`
 * matches its own (lagged, reorg-stable) oracle view. This prevents a node from unilaterally
 * locking an epoch hash the committee never agreed on — the failure mode that wedges consensus when
 * a base-layer reorg deeper than the confirmation depth straddles an epoch boundary.
 *
 * The Borsh layout (a single 32-byte hash) is identical to [`tari_sidechain::EndEpochAtom`] so the
 * layer-2 `command_hasher` output matches what L1 recomputes during checkpoint inclusion-proof
 * verification.
 */
export type EndEpochAtom = { next_epoch_hash: string };
