// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";
import type { Metadata } from "./Metadata";
import type { SubstateId } from "./SubstateId";

export type Event = { substate_id: SubstateId | null; template_address: Hash32; topic: string; payload: Metadata };
