// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionFailureCode =
  | "TemplateError"
  | "AccessDenied"
  | "AssertionFailed"
  | "InsufficientFunds"
  | "OutOfCompute"
  | "LimitExceeded"
  | "InvalidArgument"
  | "NotFound"
  | "DanglingResources"
  | "ResourceRestricted"
  | "InvalidProof"
  | "EngineInvariant"
  | "NotYetValid"
  | "Unclassified";
