// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "./Epoch";
import type { FinalizeResult } from "./FinalizeResult";

export type ExecuteResult = {
  /**
   * The finalized result to commit. If the fee transaction succeeds but the transaction fails, this will be accept.
   */
  finalize: FinalizeResult;
  /**
   * The time taken to execute the transaction (excluding finalization).
   */
  execution_time: { secs: number; nanos: number };
  /**
   * The epoch during which the transaction was executed. This may be None if consensus aborted before being able to
   * lock to an epoch.
   */
  execute_epoch: Epoch | null;
  /**
   * Total WASM metering points consumed by the transaction across all calls, including failed/aborted execution.
   * Metering is deterministic, so every validator computes the identical value for the same transaction and
   * pledged state. Used to enforce the per-block WASM points budget.
   */
  wasm_execution_points: bigint;
};
