// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transaction } from "./Transaction";
import type { TransactionExecution } from "./TransactionExecution";

export interface ExecutedTransaction {
  transaction: Transaction;
  execution: TransactionExecution;
  finalized_time: { secs: number; nanos: number } | null;
}
