// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeeBreakdown } from "./FeeBreakdown";

export type FeeCostBreakdown = { total_fees_charged: bigint; required_fees: bigint; breakdown: FeeBreakdown };
