// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeeBreakdown } from "./FeeBreakdown";

export interface FeeReceipt {
  total_fee_payment: bigint;
  total_fees_paid: bigint;
  cost_breakdown: FeeBreakdown;
}
