// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeeBreakdown } from "./FeeBreakdown";

export type FeeReceipt = {
  /**
   * The total amount of the fee payment(s)
   */
  total_fee_payment: bigint;
  /**
   * Total fees paid after refunds
   */
  total_fees_paid: bigint;
  /**
   * The amount of non-refundable fees which the user overpaid. Fees cannot be refunded when paying purely with a
   * stealth reveal (since we do not know the account/vault to refund).
   */
  total_fee_overcharge: bigint;
  /**
   * Breakdown of fee costs
   */
  cost_breakdown: FeeBreakdown;
  /**
   * The share of `total_fees_paid` that is burned rather than paid to leaders: `⌊paid × rate / 10_000⌋` at
   * the exhaust burn rate in force for the execution epoch. Settled over what was collected, so it is never
   * charged to the payer and never appears in `cost_breakdown`.
   */
  exhaust_burn: bigint;
};
