// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";
import type { FeeReceipt } from "./FeeReceipt";
import type { Hash32 } from "./Hash32";
import type { InstructionResult } from "./InstructionResult";
import type { LogEntry } from "./LogEntry";
import type { TransactionResult } from "./TransactionResult";

export type FinalizeResult = {
  transaction_hash: Hash32;
  events: Array<Event>;
  logs: Array<LogEntry>;
  execution_results: Array<InstructionResult>;
  result: TransactionResult;
  fee_receipt: FeeReceipt;
};
