// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShardGroup } from "./ShardGroup";

export type ForeignProposalAtom = { block_id: string; shard_group: ShardGroup };
