// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Off-chain documentation for a single public template function.
 */
export type FunctionDoc = { name: string; doc?: string };
