// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Representation of a 64-byte hash value
 *
 * Encoded as a CBOR byte string rather than an array of integers, so it crosses the engine
 * boundary in 66 bytes rather than ~130.
 */
export type Hash64 = string;
