// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The digest used by a [`BuiltinPredicate::HashLock`]. The preimage is hashed with no domain separation so a hashlock
 * can interoperate with an external chain's HTLC (e.g. Bitcoin's `SHA256`).
 */
export type HashAlg = "Blake2b256" | "Sha256";
