// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InputDeclaration = { substate_id: string; version: number | null; is_write: boolean };
