// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceOffsetId } from "./WorkspaceOffsetId";

/**
 * Represents an argument that can be passed to a transaction instruction. Either a literal
 * value, a reference to an item on the runtime's workspace, or a reference to a transaction
 * blob by index. Use `Blob` for large/opaque data; prefer `Literal` for small values.
 */
export type InstructionArg = { Workspace: WorkspaceOffsetId } | { Literal: string } | { Blob: number };
