// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents an argument that can be passed to a transaction instruction. Either a literal value or a reference to a
 * item on the runtime's workspace.
 */
export type InstructionArg = { Workspace: number } | { Literal: string };
