// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllocatableAddressType } from "./AllocatableAddressType";
import type { Amount } from "./Amount";
import type { ComponentAccessRules } from "./ComponentAccessRules";
import type { ComponentCall } from "./ComponentCall";
import type { ConfidentialClaim } from "./ConfidentialClaim";
import type { LogLevel } from "./LogLevel";
import type { OwnerRule } from "./OwnerRule";
import type { ResourceAddress } from "./ResourceAddress";
import type { StealthTransferStatement } from "./StealthTransferStatement";
import type { WorkspaceOffsetId } from "./WorkspaceOffsetId";

export type Instruction =
  | {
      CreateAccount: {
        public_key_address: string;
        owner_rule: OwnerRule | null;
        access_rules: ComponentAccessRules | null;
        workspace_id: WorkspaceOffsetId | null;
      };
    }
  | { CallFunction: { address: string; function: string; args: Array<any> } }
  | { CallMethod: { call: ComponentCall; method: string; args: Array<any> } }
  | { PutLastInstructionOutputOnWorkspace: { key: number } }
  | { EmitLog: { level: LogLevel; message: string } }
  | { ClaimBurn: { claim: ConfidentialClaim } }
  | { ClaimValidatorFees: { address: string } }
  | "DropAllProofsInWorkspace"
  | { AssertBucketContains: { key: WorkspaceOffsetId; resource_address: ResourceAddress; min_amount: Amount } }
  | { PublishTemplate: { binary: Array<number> } }
  | { AllocateAddress: { allocatable_type: AllocatableAddressType; workspace_id: number } }
  | {
      StealthTransfer: {
        resource_address: ResourceAddress;
        statement: StealthTransferStatement;
        revealed_input_bucket: WorkspaceOffsetId | null;
      };
    };
