// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LeaderFee = {
  /**
   * The fee payable to the leader of each involved shard group.
   */
  fee: bigint;
  /**
   * The amount burned for the whole transaction across all involved shard groups: the exhaust burn collected by
   * the executor plus the indivisible remainder from dividing the transaction fee between the leaders
   * (`fee * num_involved_shard_groups + exhaust_burn == transaction_fee + executor_exhaust_burn`).
   *
   * CONSENSUS RULE: this must equal the amount actually withheld from validators, exactly — the accumulated burn
   * in block headers determines the total supply, so it must not be re-derived with lossy arithmetic. Each shard
   * group accumulates only its portion of this into its block header burn total — see
   * `Evidence::exhaust_burn_portion`.
   */
  exhaust_burn: bigint;
};
