// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Memo = { "U256": string } | { "Message": string } | { "Bytes": string } | { "PayRefAndBytes": string };
