// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";

/**
 * An inclusion proof for a condition-tree (MAST) leaf: the sibling hashes from the leaf up to the root, bottom-first.
 */
export type MerkleProof = { siblings: Array<Hash32> };
