// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A collection of user-defined data used to describe other types, for example, non-fungible tokens or events
 */
export type Metadata = { [key in string]?: string };
