// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstructionArg } from "./InstructionArg";

export type MigrateFunction = { name: string; args: Array<InstructionArg> };
