// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface NewAccountInfo {
  name: string | null;
  key_index: bigint;
  is_default: boolean;
}
