// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonFungibleAddressContents } from "./NonFungibleAddressContents";

/**
 * The unique identifier of a non-fungible index in the Tari network
 */
export type NonFungibleAddress = NonFungibleAddressContents;
