// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The unique identification of a non-fungible token inside it's parent resource
 */
export type NonFungibleId = { U256: string } | { String: string } | { Uint32: number } | { Uint64: number };
