// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonFungibleId } from "./NonFungibleId";
import type { ResourceAddress } from "./ResourceAddress";
import type { VaultId } from "./VaultId";

export type NonFungibleToken = { vault_id: VaultId, nft_id: NonFungibleId, resource_address: ResourceAddress, data: any, mutable_data: any, is_burnt: boolean, };
