// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonFungibleId } from "./NonFungibleId";
import type { ResourceAddress } from "./ResourceAddress";

/**
 * A NonFungibleId namespaced by a ResourceAddress.
 */
export type NonFungibleAddressContents = { resource_address: ResourceAddress, id: NonFungibleId, };
