// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessRule } from "./AccessRule";

/**
 * An enum for all possible ways to specify ownership of values
 */
export type OwnerRule = "OwnedBySigner" | "None" | { "ByAccessRule": AccessRule } | { "ByPublicKey": Array<number> };
