// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Pedersen Commitment byte contents
 */
export type PedersenCommitmentBytes = string;
