// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddress } from "./ComponentAddress";
import type { Crud } from "./Crud";
import type { ReadOnly } from "./ReadOnly";
import type { ResourceAddress } from "./ResourceAddress";

/**
 * A capability the wallet daemon recognises as granted by a caller or required
 * by a handler.
 *
 * String grammar: `admin`, `webrtc`, or `<resource>:<action>[:<entity>]`.
 * Scope semantics: an unscoped grant (`None`) satisfies any required scope;
 * a scoped grant (`Some(addr)`) only satisfies an identical required scope.
 * Mutation actions (`Create`/`Update`/`Delete`) imply `Read` on the same
 * resource.
 */
export type Permission = "Admin" | { "Accounts": [Crud, ComponentAddress | null] } | { "Keys": Crud } | { "Transactions": [Crud, ComponentAddress | null] } | { "Transfer": [Crud, ComponentAddress | null] } | { "Templates": Crud } | { "Nfts": [Crud, ResourceAddress | null] } | { "Confidential": [Crud, ComponentAddress | null] } | { "StealthUtxos": [Crud, ComponentAddress | null] } | { "Validators": Crud } | { "Settings": Crud } | { "AddressBook": Crud } | { "Substates": ReadOnly } | { "BurnProofs": ReadOnly } | { "SwapPools": ReadOnly } | "Webrtc";
