// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompressedElgamalVerifiableBalance } from "./CompressedElgamalVerifiableBalance";
import type { EncryptedData } from "./EncryptedData";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";

export type PrivateOutput = {
  stealth_public_nonce: RistrettoPublicKeyBytes;
  encrypted_data: EncryptedData;
  minimum_value_promise: number | bigint;
  viewable_balance: CompressedElgamalVerifiableBalance | null;
};
