// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The unique identification of a proof during a transaction execution
 */
export type ProofId = number;
