// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "./Epoch";
import type { NodeHeight } from "./NodeHeight";
import type { ShardGroup } from "./ShardGroup";
import type { ValidatorSignatureBytes } from "./ValidatorSignatureBytes";

export type ProposalCertificate = { height: NodeHeight, header_hash: string, parent_id: string, epoch: Epoch, shard_group: ShardGroup, signatures: Array<ValidatorSignatureBytes>, decision: string, };
