// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrunedUnsealedTransactionV1 } from "./PrunedUnsealedTransactionV1";
import type { TransactionSealSignature } from "./TransactionSealSignature";

/**
 * Pruned, archive-only counterpart of `TransactionV1`. Carries blob commitments instead of
 * blob payloads. Produces the same `TransactionId` and verifies the same signatures as the
 * full form.
 */
export type PrunedTransactionV1 = { body: PrunedUnsealedTransactionV1; seal_signature: TransactionSealSignature };
