// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrunedUnsealedTransactionV1 } from "./PrunedUnsealedTransactionV1";
import type { TransactionSealSignature } from "./TransactionSealSignature";

/**
 * Pruned, archive-only counterpart of `TransactionV1`.
 *
 * Constructed only via `From<TransactionV1>` (which derives blob commitments from the full
 * blobs and drops the payloads) or via deserialization of bytes previously written by the
 * storage layer.
 */
export type PrunedTransactionV1 = { body: PrunedUnsealedTransactionV1; seal_signature: TransactionSealSignature };
