// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrunedTransactionV1 } from "./PrunedTransactionV1";

/**
 * Pruned, archive-only counterpart of `Transaction`. Carries blob commitments instead of
 * blob payloads, so API responses can omit the raw bytes while preserving the `TransactionId`,
 * signature verifiability, and the structural shape the UI needs to display.
 */
export type PrunedTransaction = { V1: PrunedTransactionV1 };
