// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrunedUnsignedTransactionV1 } from "./PrunedUnsignedTransactionV1";
import type { TransactionSignature } from "./TransactionSignature";

/**
 * Mirror of `UnsealedTransactionV1` for the pruned form.
 */
export type PrunedUnsealedTransactionV1 = { transaction: PrunedUnsignedTransactionV1, signatures: Array<TransactionSignature>, };
