// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";

/**
 * Lightweight template metadata that can be exchanged without transmitting the full WASM binary.
 */
export type PublishedTemplateMetadata = {
  /**
   * Human-readable template name extracted from the WASM ABI.
   */
  template_name: string;
  /**
   * Author's public key.
   */
  author_public_key: RistrettoPublicKeyBytes;
  /**
   * SHA-256 hash of the WASM binary.
   */
  binary_hash: Hash32;
  /**
   * Epoch at which the template was published.
   */
  at_epoch: bigint;
  /**
   * The author-provided off-chain metadata hash
   */
  metadata_hash: string | null;
};
