// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublishedTemplate = {
  /**
   * Human-readable template name extracted from the WASM ABI.
   */
  template_name: string;
  /**
   * Author's public key
   */
  author: string;
  /**
   * Binary of the template
   */
  binary: string;
  /**
   * Epoch at which the template was published
   */
  at_epoch: bigint;
  /**
   * Optional multihash of off-chain CBOR metadata
   */
  metadata_hash: string | null;
};
