// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A range proof is a cryptographic proof that a value is within a certain range without revealing the value itself.
 * This struct is used to represent the range proof bytes in a serialized format.
 * The length of the range proof is limited to a maximum size (1024 bytes) to mitigate potential denial-of-service
 * attacks.
 */
export type RangeProofBytes = string;
