// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Marker scope for resources that only support reads. Kept as a one-variant
 * enum (rather than `()`) so a future read-side extension is a non-breaking
 * addition.
 */
export type ReadOnly = "Read";
