// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbortReason } from "./AbortReason";

export type RejectReason =
  | { ExecutionFailure: string }
  | { OneOrMoreSubstatesNotFound: string }
  | { FailedToLockInputs: string }
  | { FailedToLockOutputs: string }
  | "ForeignPledgeInputConflict"
  | { ForeignShardGroupDecidedToAbort: { start_shard: number; end_shard: number; abort_reason: AbortReason } }
  | { InsufficientFeesPaid: string }
  | "FeePaymentInMainIntent"
  | { Abort: { reason: AbortReason } };
