// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleRequirement } from "./RuleRequirement";

/**
 * A rule requiring specific condition(s) to be met
 */
export type RequireRule = { "Require": RuleRequirement } | { "AnyOf": Array<RuleRequirement> } | { "AllOf": Array<RuleRequirement> } | { "MOfN": [number, Array<RuleRequirement>] };
