// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { AuthHook } from "./AuthHook";
import type { Metadata } from "./Metadata";
import type { ResourceAccessRules } from "./ResourceAccessRules";
import type { ResourceType } from "./ResourceType";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";
import type { SubstateOwnerRule } from "./SubstateOwnerRule";

export type Resource = {
  resource_type: ResourceType;
  owner_rule: SubstateOwnerRule;
  access_rules: ResourceAccessRules;
  metadata: Metadata;
  /**
   * The total supply of the resource. None means total_supply tracking is disabled.
   */
  total_supply: Amount | null;
  view_key: RistrettoPublicKeyBytes | null;
  auth_hook: AuthHook | null;
  divisibility: number;
};
