// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { NonFungibleId } from "./NonFungibleId";
import type { PedersenCommitmentBytes } from "./PedersenCommitmentBytes";
import type { PrivateOutput } from "./PrivateOutput";
import type { ResourceAddress } from "./ResourceAddress";

/**
 * Instances of a single resource kept in Buckets and Vaults
 */
export type ResourceContainer =
  | { Fungible: { address: ResourceAddress; amount: Amount; locked_amount: Amount } }
  | {
      NonFungible: {
        address: ResourceAddress;
        token_ids: Array<NonFungibleId>;
        locked_token_ids: Array<NonFungibleId>;
      };
    }
  | {
      Confidential: {
        address: ResourceAddress;
        commitments: { [key in PedersenCommitmentBytes]?: PrivateOutput };
        revealed_amount: Amount;
        locked_commitments: { [key in PedersenCommitmentBytes]?: PrivateOutput };
        locked_revealed_amount: Amount;
      };
    }
  | { Stealth: { address: ResourceAddress; revealed_amount: Amount; locked_amount: Amount } };
