// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents every possible type of resource in the Tari network.
 *
 * Resources represent digital assets managed within the Tari system, including
 * fungible tokens, non-fungible tokens (NFTs), and confidential fungible tokens.
 *
 * - **Fungible** tokens are interchangeable and divisible (e.g., currency, shares).
 * - **NonFungible** tokens represent unique, indivisible assets (e.g., collectibles).
 * - **Confidential** A type of fungible resource that uses cryptographic privacy to keep balances confidential. Funds
 *   are placed in vaults and can therefore be associated with a component that contains them, typically an Account.
 * - **Stealth** A fungible resource using the highest level of confidentiality. Funds are not kept in vaults, and each
 *   output is an independent confidential substate (kind of like creating a new unlinked vault for each currency
 *   note).
 */
export type ResourceType = "Fungible" | "NonFungible" | "Confidential" | "Stealth";
