// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The globally-unique identifier of a resource.
 */
export type ResourceAddress = string;
