// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents every possible type of resource in the Tari network.
 *
 * Resources represent digital assets managed within the Tari system, including
 * fungible tokens, non-fungible tokens (NFTs), and confidential fungible tokens.
 *
 * - **Fungible** tokens are interchangeable and divisible (e.g., currency, shares).
 * - **NonFungible** tokens represent unique, indivisible assets (e.g., collectibles).
 * - **Confidential** tokens are fungible tokens with privacy-preserving features.
 *
 * This enum is serializable/deserializable with `serde` and optionally generates
 * TypeScript bindings when the `ts` feature is enabled.
 */
export type ResourceType = "Fungible" | "NonFungible" | "Confidential";
