// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "./ResourceAddress";
import type { WorkspaceOffsetId } from "./WorkspaceOffsetId";

export type ResourceAddressRef = { Address: ResourceAddress } | { Workspace: WorkspaceOffsetId };
