// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequireRule } from "./RequireRule";

/**
 * An enum that represents the possible ways to restrict access to components or resources
 */
export type RestrictedAccessRule = { "Require": RequireRule } | { "AnyOf": Array<RestrictedAccessRule> } | { "AllOf": Array<RestrictedAccessRule> };
