// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";

/**
 * A revealed output together with the key authorised to take it.
 *
 * The revealed funds materialise as a bucket in the executing workspace rather than as a stealth output, so unlike a
 * confidential output nothing in the statement says where they end up. `receiver` supplies that: the engine requires
 * the receiver's badge in the transaction's auth scope before it creates the bucket, so a statement lifted into
 * another transaction yields its revealed funds to nobody. The receiver authorises the reveal; where the bucket goes
 * afterwards is up to the instructions that take it.
 */
export type RevealedOutput = {
  /**
   * The amount of revealed funds to output. Must be positive.
   */
  amount: Amount;
  /**
   * The public key whose badge must be in the transaction's auth scope for the revealed bucket to be created.
   */
  receiver: RistrettoPublicKeyBytes;
};
