// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddress } from "./ComponentAddress";
import type { Hash32 } from "./Hash32";
import type { NonFungibleAddress } from "./NonFungibleAddress";
import type { ResourceAddress } from "./ResourceAddress";

/**
 * Specifies a requirement for a [RequireRule].
 */
export type RuleRequirement =
  | { Resource: ResourceAddress }
  | { NonFungibleAddress: NonFungibleAddress }
  | { ScopedToComponent: ComponentAddress }
  | { ScopedToTemplate: Hash32 };
