// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";
import type { Scalar32Bytes } from "./Scalar32Bytes";

export type SchnorrSignatureBytes = { public_nonce: RistrettoPublicKeyBytes, signature: Scalar32Bytes, };
