// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ShardGroupEvidence {
  inputs: Record<string, any>;
  outputs: Record<string, number>;
  prepare_qc: string | null;
  accept_qc: string | null;
}
