// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The state versions for each shard that maps each shard managed by the ShardGroup (including the
 * global shard) to a state version.
 *
 * For example, if the ShardGroup is [1, 3], the state versions will contain 4
 * elements. The first element is always the global shard (shard 0) version. The second element is the state
 * version for shard 1, third is shard 2, and forth is shard 3.
 */
export type ShardStateVersions = { inner: number[] };
