// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessRule } from "./AccessRule";
import type { BuiltinPredicate } from "./BuiltinPredicate";
import type { TemplateFunction } from "./TemplateFunction";

export type SpendCondition =
  | { AccessRule: AccessRule }
  | { TemplateFunction: TemplateFunction }
  | { Builtin: BuiltinPredicate }
  | { All: Array<SpendCondition> };
