// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";

/**
 * How a stealth output is authorised at spend time (TIP-0006): a key path, a committed condition tree, or both.
 *
 * Modelled as an enum rather than a pair of `Option`s so the unspendable `{no key, no conditions}` state is
 * unrepresentable — by construction in memory and at the decode boundary, with no runtime invariant to enforce.
 *
 * - **Key** — a one-time "stealth" public key; spendable by proving ownership of it (a signature, via the
 *   transaction's auth scope).
 * - **Script** — the Merkle root (MAST) committing the set of alternative [`SpendCondition`] leaves; spendable by
 *   revealing one leaf plus an inclusion proof.
 * - **KeyAndScript** — either path is admissible; the per-input `SpendWitness` selects which.
 */
export type SpendAuthorization =
  | { Key: RistrettoPublicKeyBytes }
  | { Script: Hash32 }
  | { KeyAndScript: { spend_key: RistrettoPublicKeyBytes; condition_root: Hash32 } };
