// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessRule } from "./AccessRule";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";
import type { SpendScript } from "./SpendScript";

export type SpendCondition =
  | { Signed: RistrettoPublicKeyBytes }
  | { AccessRule: AccessRule }
  | { Script: SpendScript };
