// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bytes } from "./Bytes";
import type { MerkleProof } from "./MerkleProof";
import type { SpendCondition } from "./SpendCondition";

/**
 * Selects, per spent stealth input, which authorisation path the spender is exercising (TIP-0006).
 *
 * The spend is witness-driven: the committed output's [`SpendAuthorization`](super::SpendAuthorization) only gates
 * which witnesses are *admissible* (its `spend_key` for the key path, its `condition_root` for the script path); the
 * engine never assumes which path the spender picks. This type is pure data — no hashing — so it is safe to compile
 * into a template; the engine recomputes the Merkle root natively.
 */
export type SpendWitness = "KeyPath" | { ScriptPath: { leaf: SpendCondition; proof: MerkleProof; data: Bytes } };
