// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bytes } from "./Bytes";
import type { MerkleProof } from "./MerkleProof";
import type { SpendCondition } from "./SpendCondition";

/**
 * Selects, per spent stealth input, which authorisation path the spender is exercising (TIP-0006).
 */
export type SpendWitness =
  | "KeyPath"
  | { ScriptPath: { leaf: SpendCondition; proof: MerkleProof; data: Bytes } };
