// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomicCondition } from "./AtomicCondition";

/**
 * A spend-condition leaf (v0) committed in a stealth output's [`SpendAuthorization`] condition tree: a flat, non-empty
 * conjunction (logical AND) of [`AtomicCondition`]s. A script-path spend reveals one leaf and an inclusion proof; the
 * engine recomputes the root and, on a match, requires every atom in the conjunction to hold.
 *
 * Disjunction (OR) is the condition tree itself — each committed leaf is an alternative spend path — so a leaf needs
 * no OR combinator, only this AND. Atoms are not self-referential, so a leaf cannot nest another leaf: there is no
 * recursion to bound at decode and no nesting to reject at spend time.
 */
export type SpendCondition = Array<AtomicCondition>;
