// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";

/**
 * How a stealth output is authorised at spend time (TIP-0006): a key path, a committed condition tree, or both.
 */
export type SpendAuthorization =
  | { Key: RistrettoPublicKeyBytes }
  | { Script: Hash32 }
  | { KeyAndScript: { spend_key: RistrettoPublicKeyBytes; condition_root: Hash32 } };
