// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PedersenCommitmentBytes } from "./PedersenCommitmentBytes";
import type { SpendAuthorization } from "./SpendAuthorization";
import type { UtxoTag } from "./UtxoTag";

/**
 * A read-only view of a stealth output being created, as exposed to a spend script via the `SpendContext` host op.
 *
 * Confidential values remain hidden — only the commitment, `minimum_value_promise`, the output's
 * [`SpendAuthorization`] and tag are visible. This is exactly what enables covenants: a predicate can assert
 * properties of the outputs it produces (e.g. that they preserve its own `condition_root`).
 */
export type StealthOutputView = {
  commitment: PedersenCommitmentBytes;
  minimum_value_promise: bigint;
  auth: SpendAuthorization;
  tag: UtxoTag;
};
