// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StealthInputsStatement } from "./StealthInputsStatement";
import type { StealthOutputsStatement } from "./StealthOutputsStatement";

export type StealthTransferStatement = {
  inputs_statement: StealthInputsStatement;
  outputs_statement: StealthOutputsStatement;
  /**
   * Balance proof that proves that no coins were created or destroyed during the transfer (assuming the range proof
   * is valid).
   */
  balance_proof: { public_nonce: string; signature: string };
};
