// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StealthMintBalanceProof } from "./StealthMintBalanceProof";
import type { StealthOutputsStatement } from "./StealthOutputsStatement";

export type StealthMintStatement = {
  balance_proof: StealthMintBalanceProof;
  outputs_statement: StealthOutputsStatement;
};
