// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";
import type { StealthInput } from "./StealthInput";

/**
 * A statement for stealth outputs. A statement must contain confidential outputs
 */
export type StealthInputsStatement = {
  /**
   * The stealth inputs that are to be spent
   */
  inputs: Array<StealthInput>;
  /**
   * The total amount of revealed funds being spent.
   */
  revealed_amount: Amount;
  /**
   * The signer that must sign the transaction to allow these inputs to be spent.
   */
  required_signer: RistrettoPublicKeyBytes;
};
