// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";

export type StealthMintBalanceProof = {
  total_mint_amount: Amount;
  excess_signature: { public_nonce: string; signature: string };
};
