// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PedersenCommitmentBytes } from "./PedersenCommitmentBytes";

/**
 * A read-only view of a stealth input being spent, as exposed to a spend script via the `SpendContext` host op.
 *
 * Confidential values remain hidden — only the commitment is visible, exactly as the balance proof operates.
 */
export type StealthInputView = { commitment: PedersenCommitmentBytes };
