// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpendCondition } from "./SpendCondition";
import type { UnspentOutput } from "./UnspentOutput";
import type { UtxoTag } from "./UtxoTag";

export type StealthUnspentOutput = { output: UnspentOutput, spend_condition: SpendCondition, tag: UtxoTag, };
