// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PedersenCommitmentBytes } from "./PedersenCommitmentBytes";

/**
 * A statement for stealth outputs to spend as inputs.
 */
export type StealthInput = {
  /**
   * The commitment of the unspent output being spent
   */
  commitment: PedersenCommitmentBytes;
};
