// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { ValueKnowledgeProof } from "./ValueKnowledgeProof";

/**
 * Proof of knowledge of the opening to a commitment and that the commitment commits to a specific value.
 * Currently used when burning UTXOs to allow the total supply to be adjusted.
 */
export type StealthValueProof = {
  /**
   * The claimed value to prove
   */
  value: Amount;
  knowledge_proof: ValueKnowledgeProof;
};
