// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpendAuthorization } from "./SpendAuthorization";
import type { UnspentOutput } from "./UnspentOutput";
import type { UtxoTag } from "./UtxoTag";

/**
 * A stealth unspent output, authorised at spend time per its [`SpendAuthorization`] (TIP-0006).
 */
export type StealthUnspentOutput = { output: UnspentOutput; auth: SpendAuthorization; tag: UtxoTag };
