// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RangeProofBytes } from "./RangeProofBytes";
import type { RevealedOutput } from "./RevealedOutput";
import type { StealthUnspentOutput } from "./StealthUnspentOutput";

/**
 * A statement for stealth outputs. A statement must contain confidential outputs
 */
export type StealthOutputsStatement = {
  /**
   * The stealth outputs that are to be created
   */
  outputs: Array<StealthUnspentOutput>;
  /**
   * The revealed funds to output, and the key authorised to take them. When set, a bucket containing the revealed
   * stealth funds is created for `receiver`. `None` is the only encoding of "no revealed output": a zero amount is
   * rejected, so the presence of this field and the presence of a revealed bucket are the same thing.
   */
  revealed_output: RevealedOutput | null;
  /**
   * Bulletproof range proof for the output commitments proving that values are in the range
   * [minimum_value_promise, 2^64)
   */
  agg_range_proof: RangeProofBytes;
};
