// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { RangeProofBytes } from "./RangeProofBytes";
import type { UnspentOutput } from "./UnspentOutput";

/**
 * A statement for stealth outputs. A statement must contain confidential outputs
 */
export type StealthOutputsStatement = {
  /**
   * Proof of the confidential resources that are going to be transferred to the receiver
   */
  outputs: Array<UnspentOutput>;
  /**
   * The amount of revealed funds to output. If this is a positive (non-zero) value, a bucket containing the
   * revealed stealth funds is created.
   */
  revealed_output_amount: Amount;
  /**
   * Bulletproof range proof for the output commitments proving that values are in the range
   * [minimum_value_promise, 2^64)
   */
  agg_range_proof: RangeProofBytes;
};
