// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PedersenCommitmentBytes } from "./PedersenCommitmentBytes";
import type { SchnorrSignatureBytes } from "./SchnorrSignatureBytes";

/**
 * A statement for stealth outputs. A statement must contain confidential outputs
 */
export type StealthInput = {
  /**
   * The commitment of the unspent output being spent
   */
  commitment: PedersenCommitmentBytes;
  /**
   * Signature that proves ownership of the unspent output. This must be signed by the owner_public_key of the
   * output.
   */
  owner_proof: SchnorrSignatureBytes;
};
