// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CovenantBalanceClaim } from "./CovenantBalanceClaim";
import type { SchnorrSignatureBytes } from "./SchnorrSignatureBytes";
import type { StealthInputsStatement } from "./StealthInputsStatement";
import type { StealthOutputsStatement } from "./StealthOutputsStatement";

export type StealthTransferStatement = {
  inputs_statement: StealthInputsStatement;
  outputs_statement: StealthOutputsStatement;
  /**
   * Balance proof that proves that no coins were created or destroyed during the transfer (assuming the range proof
   * is valid). This may be None, if and only if, the transfer is revealed-only (i.e. no stealth inputs or outputs).
   */
  balance_proof: SchnorrSignatureBytes | null;
  /**
   * Covenant sub-balance proofs (TIP-0006), one per input partition whose `SpendCondition::Script` predicate
   * requires value conservation. Empty when no spent input gates on a covenant.
   */
  covenant_claims: Array<CovenantBalanceClaim>;
};
