// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaimedOutputTombstone } from "./ClaimedOutputTombstone";
import type { Component } from "./Component";
import type { NonFungibleContainer } from "./NonFungibleContainer";
import type { PublishedTemplate } from "./PublishedTemplate";
import type { Resource } from "./Resource";
import type { TransactionReceipt } from "./TransactionReceipt";
import type { Utxo } from "./Utxo";
import type { ValidatorFeePool } from "./ValidatorFeePool";
import type { Vault } from "./Vault";

export type SubstateValue =
  | { Component: Component }
  | { Resource: Resource }
  | { Vault: Vault }
  | { NonFungible: NonFungibleContainer }
  | { ClaimedOutputTombstone: ClaimedOutputTombstone }
  | { TransactionReceipt: TransactionReceipt }
  | { Template: PublishedTemplate }
  | { ValidatorFeePool: ValidatorFeePool }
  | { Utxo: Utxo };
