// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddress } from "./ComponentAddress";
import type { NonFungibleAddress } from "./NonFungibleAddress";
import type { PublishedTemplateAddress } from "./PublishedTemplateAddress";
import type { ResourceAddress } from "./ResourceAddress";
import type { TransactionReceiptAddress } from "./TransactionReceiptAddress";
import type { UnclaimedConfidentialOutputAddress } from "./UnclaimedConfidentialOutputAddress";
import type { UtxoAddress } from "./UtxoAddress";
import type { ValidatorFeePoolAddress } from "./ValidatorFeePoolAddress";
import type { VaultId } from "./VaultId";

/**
 * Base object address, version tuples
 */
export type SubstateId =
  | { Component: ComponentAddress }
  | { Resource: ResourceAddress }
  | { Vault: VaultId }
  | { UnclaimedConfidentialOutput: UnclaimedConfidentialOutputAddress }
  | { NonFungible: NonFungibleAddress }
  | { TransactionReceipt: TransactionReceiptAddress }
  | { Template: PublishedTemplateAddress }
  | { ValidatorFeePool: ValidatorFeePoolAddress }
  | { Utxo: UtxoAddress };
