// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "./Epoch";

export type SubstateDestroyed = { at_epoch: Epoch; at_state_version: bigint };
