// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateCreated } from "./SubstateCreated";
import type { SubstateDestroyed } from "./SubstateDestroyed";
import type { SubstateId } from "./SubstateId";
import type { SubstateValue } from "./SubstateValue";

export type SubstateRecord = {
  substate_id: SubstateId;
  version: number;
  substate_value: SubstateValue | null;
  state_hash: string;
  created: SubstateCreated;
  destroyed: SubstateDestroyed | null;
};
