// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "./Epoch";
import type { Shard } from "./Shard";

export type SubstateCreated = { at_epoch: Epoch; in_shard: Shard; at_state_version: bigint };
