// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitmentSignatureBytes } from "./CommitmentSignatureBytes";
import type { RangeProofBytes } from "./RangeProofBytes";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";
import type { StealthTransferStatement } from "./StealthTransferStatement";
import type { UnclaimedConfidentialOutputAddress } from "./UnclaimedConfidentialOutputAddress";

export type TariStealthClaim = {
  /**
   * This is typically the public nonce that the UTXO was burnt with
   */
  burn_public_key: RistrettoPublicKeyBytes;
  output_address: UnclaimedConfidentialOutputAddress;
  range_proof: RangeProofBytes;
  proof_of_knowledge: CommitmentSignatureBytes;
  transfer_statement: StealthTransferStatement | null;
};
