// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Off-chain template metadata, serialized as CBOR for hashing and verification.
 *
 * Template authors populate these fields via their `Cargo.toml` `[package]` and
 * `[package.metadata.tari-template]` sections. The CBOR encoding of this struct is
 * hashed to produce a [`MetadataHash`] that is stored on-chain alongside the template binary.
 */
export type TemplateMetadata = {
  schema_version: number;
  name: string;
  version: string;
  description?: string;
  tags?: Array<string>;
  category?: string | null;
  repository?: string | null;
  /**
   * The commit hash of the source code used to build this template, for reproducible build verification.
   */
  commit_hash?: { Sha1: string } | null;
  documentation?: string | null;
  homepage?: string | null;
  license?: string | null;
  logo_url?: string | null;
  /**
   * The template address of a previous version that this template supersedes.
   */
  supersedes?: string | null;
  extra?: { [key in string]?: string };
};
