// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "./Epoch";
import type { NodeHeight } from "./NodeHeight";
import type { ValidatorSignatureBytes } from "./ValidatorSignatureBytes";

export interface TimeoutCertificate {
  epoch: Epoch;
  height: NodeHeight;
  signatures: Array<ValidatorSignatureBytes>;
}
