// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "./Epoch";
import type { NodeHeight } from "./NodeHeight";
import type { ValidatorSignatureBytes } from "./ValidatorSignatureBytes";

export type TimeoutCertificate = {
  epoch: Epoch;
  height: NodeHeight;
  /**
   * A quorum of validator signatures that sign the timeout certificate.
   */
  signatures: Array<ValidatorSignatureBytes>;
};
