// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSummary } from "./DiffSummary";
import type { Epoch } from "./Epoch";
import type { Event } from "./Event";
import type { FeeReceipt } from "./FeeReceipt";
import type { FinalizeOutcome } from "./FinalizeOutcome";
import type { Hash32 } from "./Hash32";
import type { ValidatorFeeWithdrawal } from "./ValidatorFeeWithdrawal";

export type TransactionReceipt = {
  outcome: FinalizeOutcome;
  diff_summary: DiffSummary;
  fee_withdrawals: Array<ValidatorFeeWithdrawal>;
  events: Array<Event>;
  fee_receipt: FeeReceipt;
  epoch: Epoch;
  intent_commitment: Hash32;
};
