// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";
import type { SchnorrSignatureBytes } from "./SchnorrSignatureBytes";

export type TransactionSignature = { public_key: RistrettoPublicKeyBytes, signature: SchnorrSignatureBytes, };
