// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionV1 } from "./TransactionV1";

export type Transaction = { V1: TransactionV1 };
