// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSummary } from "./DiffSummary";
import type { Epoch } from "./Epoch";
import type { Event } from "./Event";
import type { FeeReceipt } from "./FeeReceipt";
import type { FinalizeOutcome } from "./FinalizeOutcome";
import type { Hash32 } from "./Hash32";
import type { ValidatorFeeWithdrawal } from "./ValidatorFeeWithdrawal";

export type TransactionReceipt = {
  outcome: FinalizeOutcome;
  diff_summary: DiffSummary;
  fee_withdrawals: Array<ValidatorFeeWithdrawal>;
  events: Array<Event>;
  fee_receipt: FeeReceipt;
  epoch: Epoch;
  /**
   * Commitment to the transaction's intent: every field the signers authorized (network, fee
   * instructions, instructions, inputs, epoch bounds, flags and blob commitments), excluding the
   * signatures themselves.
   *
   * The receipt is already bound to the transaction transitively — it is addressed by the
   * transaction id — but reproducing that id requires the signatures and the seal signature, so
   * establishing the link that way reveals the signers. This commitment is over the same
   * projection minus the signatures, so whoever holds the transaction can link it to this
   * receipt without revealing who authorized it. It identifies the intent, not the signers:
   * transactions differing only in who signed them share a commitment.
   */
  intent_commitment: Hash32;
};
