// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockId } from "./BlockId";
import type { Decision } from "./Decision";
import type { Epoch } from "./Epoch";
import type { Evidence } from "./Evidence";
import type { LeaderFee } from "./LeaderFee";
import type { LockedEpoch } from "./LockedEpoch";
import type { TransactionPoolStage } from "./TransactionPoolStage";

export type TransactionPoolRecord = {
  transaction_id: string;
  evidence: Evidence;
  is_global: boolean;
  transaction_fee: bigint;
  leader_fee: LeaderFee | null;
  stage: TransactionPoolStage;
  pending_stage: TransactionPoolStage | null;
  original_decision: Decision;
  local_decision: Decision | null;
  remote_decision: Decision | null;
  is_ready: boolean;
  /**
   * The maximum epoch for which this transaction is valid.
   */
  max_epoch: Epoch | null;
  /**
   * Epoch to use when executing the transaction. This updates as foreign proposals are received
   * until the transaction is executed.
   */
  locked_epoch: LockedEpoch | null;
  last_updated: string;
  last_updated_in_block: BlockId | null;
};
