// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecuteResult } from "./ExecuteResult";
import type { VersionedSubstateIdLockIntent } from "./VersionedSubstateIdLockIntent";

export interface TransactionExecution {
  result: ExecuteResult;
  resolved_inputs: Array<VersionedSubstateIdLockIntent>;
  resulting_outputs: Array<VersionedSubstateIdLockIntent>;
}
