// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSummary } from "./DiffSummary";
import type { Event } from "./Event";
import type { FeeReceipt } from "./FeeReceipt";
import type { LogEntry } from "./LogEntry";
import type { ValidatorFeeWithdrawal } from "./ValidatorFeeWithdrawal";

export type TransactionReceipt = {
  diff_summary: DiffSummary;
  fee_withdrawals: Array<ValidatorFeeWithdrawal>;
  events: Array<Event>;
  logs: Array<LogEntry>;
  fee_receipt: FeeReceipt;
};
