// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Actions on a transaction request. Deliberately not [`Crud`]: approving is
 * not a mutation of the request, it is the act that authorises the value
 * transfer the request describes. Modelling it as `Update` would let any
 * grant carrying edit rights approve.
 */
export type TxRequestAction = "Read" | "Create" | "Approve";
