// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnsealedTransactionV1 } from "./UnsealedTransactionV1";

export type UnsealedTransaction = { V1: UnsealedTransactionV1 };
