// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionSignature } from "./TransactionSignature";
import type { UnsignedTransactionV1 } from "./UnsignedTransactionV1";

export interface UnsealedTransactionV1 {
  transaction: UnsignedTransactionV1;
  signatures: Array<TransactionSignature>;
}
