// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnsignedTransactionV1 } from "./UnsignedTransactionV1";

export type UnsignedTransaction = { V1: UnsignedTransactionV1 };
