// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptedData } from "./EncryptedData";
import type { PedersenCommitmentBytes } from "./PedersenCommitmentBytes";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";
import type { ViewableBalanceProof } from "./ViewableBalanceProof";

/**
 * An unspent output that does not reveal the value and the owner of the coin it represents.
 *
 * Unspent outputs contain:
 * - **commitment** - the Pedersen commitment k.G + v.H
 * - **sender_public_nonce** - the sender-provided public nonce that is used as part of a DH key exchange to generate
 *   the decryption key for the encrypted data.
 * - **encrypted_data** - the encrypted data that contains the encrypted mask and value.
 * - **viewable_balance_proof** - an optional verifiable balance proof that must be provided and valid if the view key
 *   is enabled for a resource.
 */
export type UnspentOutput = {
  commitment: PedersenCommitmentBytes;
  /**
   * Public nonce (R) that was used to generate the commitment mask
   */
  sender_public_nonce: RistrettoPublicKeyBytes;
  /**
   * Encrypted mask and value for the recipient.
   */
  encrypted_data: EncryptedData;
  minimum_value_promise: bigint;
  /**
   * If the view key is enabled for a given resource, this proof MUST be provided, otherwise it MUST NOT.
   */
  viewable_balance_proof: ViewableBalanceProof | null;
};
