// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "./Hash32";
import type { SubstateId } from "./SubstateId";

export type UpSubstate = { substate_id: SubstateId, version: number, value_hash: Hash32, };
