// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivateOutput } from "./PrivateOutput";

export type Utxo = { output: PrivateOutput | null; is_frozen: boolean };
