// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfidentialOutput } from "./ConfidentialOutput";

export type Utxo = { output: ConfidentialOutput; is_frozen: boolean };
