// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shard } from "./Shard";
import type { StateVersion } from "./StateVersion";
import type { UtxoAddress } from "./UtxoAddress";

export type UtxoSpent = { address: UtxoAddress; version: number; shard: Shard; state_version: StateVersion };
