// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";
import type { UtxoId } from "./UtxoId";
import type { UtxoTag } from "./UtxoTag";

export type UtxoUnspent = { id: UtxoId; version: number; tag: UtxoTag; public_nonce: RistrettoPublicKeyBytes };
