// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "./ResourceAddress";
import type { UtxoId } from "./UtxoId";

/**
 * A NonFungibleId namespaced by a ResourceAddress.
 */
export type UtxoAddressContents = { resource_address: ResourceAddress, id: UtxoId, };
