// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shard } from "./Shard";
import type { StateVersion } from "./StateVersion";
import type { UtxoStateUpdateSet } from "./UtxoStateUpdateSet";

export type UtxoUpdateSet = {
  shard_updates: { [key in Shard]?: UtxoStateUpdateSet };
  per_shard_high_watermark: Array<[Shard, StateVersion]>;
};
