// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A 4-byte tag associated with a UTXO. This can be used to more quickly identify _possible_ ownership of a UTXO
 * without needing to fully download and verify all UTXOs.
 * 4 bytes gives a reasonable trade-off between initial download size and utxo size.
 */
export type UtxoTag = number;
