// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputBody } from "./OutputBody";
import type { SpendCondition } from "./SpendCondition";
import type { UtxoTag } from "./UtxoTag";

export type UtxoOutput = { output: OutputBody; spend_condition: SpendCondition; tag: UtxoTag };
