// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shard } from "./Shard";
import type { StateVersion } from "./StateVersion";
import type { UtxoUpdate } from "./UtxoUpdate";

export type UtxoQueryResponse = { updates: Array<UtxoUpdate>; per_shard_high_watermark: Array<[Shard, StateVersion]> };
