// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StateVersion } from "./StateVersion";
import type { WalletUtxoUpdate } from "./WalletUtxoUpdate";

export type UtxoStateUpdateSet = { updates: Array<WalletUtxoUpdate>; max_state_version: StateVersion };
