// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivateOutput } from "./PrivateOutput";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";
import type { UtxoTagByte } from "./UtxoTagByte";

export type UtxoOutput = {
  output: PrivateOutput;
  /**
   * The public key that must prove ownership of this UTXO. This is typically a one time "stealth" public key but is
   * selected by the client.
   */
  owner_public_key: RistrettoPublicKeyBytes;
  tag: UtxoTagByte;
};
