// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UtxoOutput } from "./UtxoOutput";

export type Utxo = { output: UtxoOutput | null, is_frozen: boolean, };
