// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shard } from "./Shard";
import type { StateVersion } from "./StateVersion";
import type { Utxo } from "./Utxo";
import type { UtxoAddress } from "./UtxoAddress";

export type UtxoUnspent = {
  address: UtxoAddress;
  version: number;
  shard: Shard;
  state_version: StateVersion;
  utxo: Utxo;
};
