// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidatorFeePoolAddress } from "./ValidatorFeePoolAddress";

export interface ValidatorFeeWithdrawal {
  address: ValidatorFeePoolAddress;
  amount: bigint;
}
