// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceContainer } from "./ResourceContainer";
import type { VaultFreezeFlags } from "./VaultFreezeFlags";

export type Vault = { resource_container: ResourceContainer; freeze_flags: VaultFreezeFlags };
