// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A vault's unique identification in the Tari network
 */
export type VaultId = string;
