// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PedersenCommitmentBytes } from "./PedersenCommitmentBytes";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";
import type { Scalar32Bytes } from "./Scalar32Bytes";

export interface ViewableBalanceProof {
  elgamal_encrypted: RistrettoPublicKeyBytes;
  elgamal_public_nonce: RistrettoPublicKeyBytes;
  c_prime: PedersenCommitmentBytes;
  e_prime: RistrettoPublicKeyBytes;
  r_prime: RistrettoPublicKeyBytes;
  s_v: Scalar32Bytes;
  s_m: Scalar32Bytes;
  s_r: Scalar32Bytes;
}
