// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { FinalizeResult } from "./FinalizeResult";
import type { NewAccountInfo } from "./NewAccountInfo";
import type { ProposalCertificate } from "./ProposalCertificate";
import type { SubstateRequirement } from "./SubstateRequirement";
import type { Transaction } from "./Transaction";
import type { TransactionStatus } from "./TransactionStatus";

export interface WalletTransaction {
  transaction: Transaction;
  status: TransactionStatus;
  finalize: FinalizeResult | null;
  final_fee: Amount | null;
  qcs: Array<ProposalCertificate>;
  execution_time: { secs: number; nanos: number } | null;
  finalized_time: { secs: number; nanos: number } | null;
  required_substates: Array<SubstateRequirement>;
  new_account_info: NewAccountInfo | null;
  is_dry_run: boolean;
  last_update_time: string;
}
