cognitive-complexity-threshold = 15
too-many-arguments-threshold = 7
# Set from 200 to size of a RistrettoPublicKey
enum-variant-size-threshold = 216
allow-indexing-slicing-in-tests = true
suppress-restriction-lint-in-const = true
large-error-threshold = 192
