/*
 * ootle_sdk.h — flat C ABI for the Tari Ootle fat core (ootle-sdk-core).
 *
 * GENERATED by cbindgen from crates/ootle_sdk_ffi_c. Do not edit by hand; run
 * `cargo build -p ootle_sdk_ffi_c` to regenerate.
 */

#ifndef OOTLE_SDK_H
#define OOTLE_SDK_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
typedef struct OotlePartialTransaction OotlePartialTransaction;
typedef struct OotleStealthPartialTransaction OotleStealthPartialTransaction;

/**
 * The result envelope every `extern "C"` op returns by value.
 *
 * `error_code`/`error_message`/`data_json` are heap-allocated, NUL-terminated UTF-8 C strings owned
 * by the **host**; free them all in one call with [`ootle_result_free`]. On success `error_code` and
 * `error_message` are the empty string `""` (never NULL); on error they carry the stable
 * [`OotleSdkError::code`] and the human-readable message, and the output fields are NULL/empty.
 *
 * Exactly one of the output channels is populated per op: ops that return JSON set `data_json` (and
 * leave `handle` NULL); ops that return the opaque handle set `handle` (and leave `data_json` NULL).
 * [`ootle_result_free`] frees the three strings but **never** the handle — the handle has its own
 * lifecycle (see the crate docs).
 */
typedef struct {
    /**
     * `1` on success, `0` on error. A plain `uint8_t` (not C `_Bool`) so the field has an identical,
     * well-defined layout for every C / cgo host, including older C compilers without `<stdbool.h>`.
     */
    uint8_t ok;
    /**
     * The stable error code (e.g. `"PARSE"`, `"KEY"`, `"INTERNAL"`) or `""` on success. Host-owned.
     */
    char *error_code;
    /**
     * The human-readable error message or `""` on success. Host-owned.
     */
    char *error_message;
    /**
     * The JSON output for ops that return data, else NULL. Host-owned.
     */
    char *data_json;
    /**
     * The opaque handle for ops that return one, else NULL. Freed with
     * [`ootle_partial_transaction_free`], **not** by [`ootle_result_free`].
     */
    OotlePartialTransaction *handle;
} OotleResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Builds, deterministically seals (pinned nonces) and BOR-encodes a public transfer in one call.
 *
 * `intent_json` is a `PublicTransferIntent`; `keys_json` is `{account_secret, auth_nonce, seal_nonce
 * [, seal_secret]}` (all lowercase hex). On success `data_json` is the `EncodedPublicTransfer`
 * (`{encoded_transaction, transaction_id}`, lowercase hex). Reproducible byte-for-byte.
 *
 * # Safety
 * `intent_json` and `keys_json` must be valid NUL-terminated UTF-8 C strings. The returned envelope
 * must be freed with [`ootle_result_free`].
 */
OotleResult ootle_build_and_encode_public_transfer(uint8_t network,
                                                   const char *intent_json,
                                                   const char *keys_json);

/**
 * Production (random-nonce) counterpart of [`ootle_build_and_encode_public_transfer`]. `keys_json` is
 * `{account_secret}` (lowercase hex). The bytes/id are **not** reproducible — for real submission.
 *
 * # Safety
 * As [`ootle_build_and_encode_public_transfer`].
 */
OotleResult ootle_build_and_encode_public_transfer_production(uint8_t network,
                                                              const char *intent_json,
                                                              const char *keys_json);

/**
 * Mints a fresh **account** keypair from `OsRng` (production). On success `data_json` is
 * `{"account_secret":"<hex32>","account_public_key":"<hex32>"}` (lowercase hex); no handle. The
 * bytes are non-reproducible by design.
 *
 * # Secrets
 * `data_json` carries the **plaintext** account secret. The facade does not zeroize the returned C
 * string (it is owned by the host); the host is responsible for scrubbing / limiting the lifetime of
 * the buffer after reading the secret — same posture as the stealth fns for incoming secret strings.
 *
 * # Safety
 * The returned envelope must be freed with [`ootle_result_free`].
 */
OotleResult ootle_generate_account_key(void);

/**
 * Mints a fresh **view** keypair from `OsRng` (production). On success `data_json` is
 * `{"view_secret":"<hex32>","view_public_key":"<hex32>"}` (lowercase hex); no handle.
 * Non-reproducible by design.
 *
 * # Secrets
 * `data_json` carries the **plaintext** view secret; the host must scrub it (see
 * [`ootle_generate_account_key`]).
 *
 * # Safety
 * As [`ootle_generate_account_key`].
 */
OotleResult ootle_generate_view_key(void);

/**
 * Deterministically derives the **account** keypair from a 32-byte seed (no RNG). `seed_hex` is the
 * lowercase-hex 32-byte seed. On success `data_json` is
 * `{"account_secret":"<hex32>","account_public_key":"<hex32>"}`. Reproducible byte-for-byte.
 *
 * Bad / odd / uppercase / wrong-length `seed_hex` ⇒ `"PARSE"`.
 *
 * # Secrets
 * `data_json` carries the **plaintext** account secret; the host must scrub it (see
 * [`ootle_generate_account_key`]). The facade does not zeroize the incoming `seed_hex` C string either.
 *
 * # Safety
 * `seed_hex` must be a valid NUL-terminated UTF-8 C string. The returned envelope must be freed with
 * [`ootle_result_free`].
 */
OotleResult ootle_derive_account_key_from_seed(const char *seed_hex);

/**
 * Deterministically derives the **view** keypair from a 32-byte seed (no RNG). `seed_hex` is the
 * lowercase-hex 32-byte seed. On success `data_json` is
 * `{"view_secret":"<hex32>","view_public_key":"<hex32>"}`. Reproducible byte-for-byte.
 *
 * Bad / odd / uppercase / wrong-length `seed_hex` ⇒ `"PARSE"`.
 *
 * # Secrets
 * `data_json` carries the **plaintext** view secret; the host must scrub it (see
 * [`ootle_generate_account_key`]).
 *
 * # Safety
 * As [`ootle_derive_account_key_from_seed`].
 */
OotleResult ootle_derive_view_key_from_seed(const char *seed_hex);

/**
 * Derives the canonical **account component address** from an account public key.
 *
 * `account_public_key_hex` is the lowercase-hex 32-byte account public key. On success `data_json` is
 * `{"component_address":"component_<hex>"}`; no handle. Uses the same engine derivation as the
 * transfer builder, so a derived address matches where the builder places a recipient account.
 * Network-independent (template + pk only).
 *
 * Bad / odd / uppercase / wrong-length `account_public_key_hex` ⇒ `"PARSE"`. The bytes are not
 * validated as a canonical curve point (the engine hashes them as-is), so there is no `"KEY"` path.
 *
 * # Safety
 * `account_public_key_hex` must be a valid NUL-terminated UTF-8 C string. The returned envelope must
 * be freed with [`ootle_result_free`].
 */
OotleResult ootle_derive_account_address(const char *account_public_key_hex);

/**
 * Parses an address string into a kind-tagged record, dispatching on prefix.
 *
 * `address_str` is either a `component_<hex>` / `resource_<hex>` engine substate id **or** an
 * `otl_…` bech32m identity / payment address. On success `data_json` is the kind-tagged
 * [`ParsedAddress`](ootle_sdk_core::ParsedAddress):
 * - substate: `{"kind":"component"|"resource","canonical":"…_<hex>"}`;
 * - identity: `{"kind":"identity","network":"<keyword>","account_key":"<hex>","view_only_key":"<hex>",
 *   "pay_ref":"<hex>"?,"bech32m":"otl_…"}` (`pay_ref` is absent when none).
 *
 * An unknown prefix, a malformed substate id, or a bad bech32m string (checksum / HRP / length /
 * oversize pay_ref) ⇒ `"PARSE"`; no handle.
 *
 * # Safety
 * `address_str` must be a valid NUL-terminated UTF-8 C string. The returned envelope must be freed
 * with [`ootle_result_free`].
 */
OotleResult ootle_parse_address(const char *address_str);

/**
 * Formats an `otl_…` identity / payment address (bech32m) from its parts.
 *
 * `network` is the L1 discriminant byte (selects the network-qualified HRP — `otl_` MainNet,
 * `otl_loc_` LocalNet, `otl_esm_` Esmeralda, …). `account_key_hex` / `view_only_key_hex` are the
 * lowercase-hex 32-byte public keys. `pay_ref_hex` is a **nullable** lowercase-hex payment reference
 * (pass NULL for none); over 64 bytes ⇒ `"PARSE"`. On success `data_json` is `{"bech32m":"otl_…"}`;
 * no handle.
 *
 * Bad / odd / uppercase key hex or pay_ref hex ⇒ `"PARSE"`.
 *
 * # Safety
 * `account_key_hex` and `view_only_key_hex` must be valid NUL-terminated UTF-8 C strings.
 * `pay_ref_hex` must be NULL or such a string. The returned envelope must be freed with
 * [`ootle_result_free`].
 */
OotleResult ootle_format_identity_address(uint8_t network,
                                          const char *account_key_hex,
                                          const char *view_only_key_hex,
                                          const char *pay_ref_hex);

/**
 * Builds the public-transfer unsigned tx + the want list to resolve it.
 *
 * On success the envelope carries the opaque handle (in `handle`) and the want list in `data_json`
 * (`{"want_list":[…]}` — the serde form of `WantList`'s inner `Vec<WantItem>`). The host fetches the
 * wanted substates, then drives [`ootle_apply_fetched_substates`].
 *
 * # Safety
 * `intent_json` must be a valid NUL-terminated UTF-8 C string. The returned envelope must be freed
 * with [`ootle_result_free`]; the returned `handle` must be consumed by a later call or freed with
 * [`ootle_partial_transaction_free`].
 */
OotleResult ootle_build_unsigned(uint8_t network,
                                 const char *intent_json);

/**
 * Builds an unsigned tx from a **generic instruction list** + the want list to resolve it.
 *
 * Lowers a generic instruction list + typed-arg DSL ([`GenericTransactionIntent`]) into an unsigned
 * transaction. Returns the same opaque handle + want-list envelope as [`ootle_build_unsigned`]; finish
 * it with [`ootle_apply_fetched_substates`] then [`ootle_seal_and_encode`] /
 * [`ootle_seal_and_encode_production`].
 *
 * On success the envelope carries the opaque handle (in `handle`) and the want list in `data_json`
 * (`{"want_list":[…]}`). Bad intent JSON ⇒ `"PARSE"`; an out-of-range blob index / unbound workspace
 * label ⇒ `"VALIDATION"` (the core's structural checks).
 *
 * # Safety
 * `intent_json` must be a valid NUL-terminated UTF-8 C string. The returned envelope must be freed
 * with [`ootle_result_free`]; the returned `handle` must be consumed by a later call or freed with
 * [`ootle_partial_transaction_free`].
 */
OotleResult ootle_build_unsigned_instructions(uint8_t network,
                                              const char *intent_json);

/**
 * Builds an unsigned **faucet claim** + the want list to resolve it.
 *
 * Emits a complete self-funding claim (create the recipient account, fund it from the network faucet,
 * pay the fee from it) with the faucet's full input set derived internally. Returns the same opaque
 * handle + want-list envelope as [`ootle_build_unsigned`]; finish it with
 * [`ootle_apply_fetched_substates`] + [`ootle_seal_and_encode`].
 *
 * `intent_json` is a [`FaucetClaimIntent`] (`{"recipient_public_key":"<hex>","fee":<µTari>,…}`). On
 * success the envelope carries the handle and `{"want_list":[…]}`. Bad intent JSON ⇒ `"PARSE"`.
 *
 * # Safety
 * `intent_json` must be a valid NUL-terminated UTF-8 C string. The returned envelope must be freed
 * with [`ootle_result_free`]; the returned `handle` must be consumed by a later call or freed with
 * [`ootle_partial_transaction_free`].
 */
OotleResult ootle_build_faucet_claim(uint8_t network,
                                     const char *intent_json);

/**
 * Applies a fetched batch of substates to the partial and reports resolution status.
 *
 * **Consumes** `handle` (it is taken by value — treat the pointer you passed as invalid afterwards,
 * even on error). `fetched_json` is a JSON array of `FetchedSubstate`. On success the envelope
 * carries a (possibly new) handle to thread forward and `data_json`:
 * - `{"status":"resolved"}` — ready to seal via [`ootle_seal_and_encode`]; or
 * - `{"status":"need_more","want_list":[…],"fetch_ids":[…]}` — fetch the substates named in **`fetch_ids`** (the
 *   authoritative concrete next-fetch set, including vault ids the core discovered inside a fetched component) and
 *   call this again on the returned handle. `want_list` is the informational semantic remainder; fetch `fetch_ids`,
 *   not the want-list seeds.
 *
 * On error the input handle is still consumed and freed; the returned envelope carries no handle.
 *
 * # Safety
 * `handle` must be a non-null pointer previously returned by [`ootle_build_unsigned`] /
 * [`ootle_apply_fetched_substates`] and not yet consumed. `fetched_json` must be a valid
 * NUL-terminated UTF-8 C string. The returned envelope must be freed with [`ootle_result_free`].
 */
OotleResult ootle_apply_fetched_substates(OotlePartialTransaction *handle,
                                          const char *fetched_json);

/**
 * Seals (deterministically, pinned nonces) and BOR-encodes a **resolved** partial.
 *
 * **Consumes** `handle`. `keys_json` is `{account_secret, auth_nonce, seal_nonce [, seal_secret]}`
 * (lowercase hex). On success `data_json` is the `EncodedPublicTransfer`. A still-unresolved partial
 * ⇒ a `RESOLUTION` error (the handle is still consumed). No handle is returned.
 *
 * # Safety
 * `handle` must be a non-null, not-yet-consumed pointer from the two-phase ops. `keys_json` must be a
 * valid NUL-terminated UTF-8 C string. The returned envelope must be freed with [`ootle_result_free`].
 * Do **not** free `handle` afterwards — it is consumed here.
 */
OotleResult ootle_seal_and_encode(OotlePartialTransaction *handle,
                                  const char *keys_json);

/**
 * Production (random-nonce) counterpart of [`ootle_seal_and_encode`]. **Consumes** `handle`.
 * `keys_json` is `{account_secret}`. The bytes/id are not reproducible.
 *
 * # Safety
 * As [`ootle_seal_and_encode`].
 */
OotleResult ootle_seal_and_encode_production(OotlePartialTransaction *handle,
                                             const char *keys_json);

/**
 * Derives the serializable [`UnsignedTransactionRecord`] party A ships to party B, from a resolved
 * public handle. **Borrows** the handle (does **not** consume it) so A can ship the record JSON *and*
 * keep the handle to seal later with [`ootle_seal_and_encode_with_auth`].
 *
 * On success `data_json` is the `UnsignedTransactionRecord` JSON (`{"unsigned": <UnsignedTransaction>}`).
 * An unresolved partial ⇒ a `RESOLUTION` error (the handle is left intact).
 *
 * # Safety
 * `handle` must be a non-null, not-yet-consumed public handle. The returned envelope must be freed
 * with [`ootle_result_free`]. The handle is **not** consumed; free it with
 * [`ootle_partial_transaction_free`] (or consume it via a seal fn) exactly once afterwards.
 */
OotleResult ootle_unsigned_record_for_cosign(const OotlePartialTransaction *handle);

/**
 * Authorizes party A's serialized unsigned transaction record (production path: fresh random Schnorr
 * nonce), committing to A's seal public key. Called by party B.
 *
 * `unsigned_json` is the `UnsignedTransactionRecord` JSON A shipped (`{"unsigned": <UnsignedTransaction
 * JSON>}`, from [`ootle_unsigned_record_for_cosign`]). `seal_public_key_hex` is A's seal public key
 * (lowercase hex). `signer_secret_hex` is B's secret key (lowercase hex). On success `data_json` is
 * `{ "authorization": { "public_key": "<hex>", "signature": "<hex>" } }`.
 *
 * `network` is accepted for API symmetry (validated against the known discriminants); the signing
 * message is derived from the unsigned record, which already carries the network.
 *
 * Bad key hex ⇒ `KEY`; a non-canonical secret scalar ⇒ `KEY`; bad/odd/uppercase seal-pk hex ⇒ `PARSE`;
 * malformed `unsigned_json` ⇒ `PARSE`.
 *
 * # Safety
 * `unsigned_json`, `seal_public_key_hex`, and `signer_secret_hex` must each be a valid NUL-terminated
 * UTF-8 C string. The returned envelope must be freed with [`ootle_result_free`]. `signer_secret_hex`
 * crosses as transient hex and is dropped at the end of the call; the facade does not zero it.
 */
OotleResult ootle_add_signature(uint8_t network,
                                const char *unsigned_json,
                                const char *seal_public_key_hex,
                                const char *signer_secret_hex);

/**
 * Seals a resolved partial **with attached authorizations** (deterministically, pinned nonces) and
 * BOR-encodes it. **Consumes** `handle` (exactly like [`ootle_seal_and_encode`]).
 *
 * `keys_json` reuses the `DeterministicKeysJson` mirror (`{account_secret, auth_nonce, seal_nonce
 * [, seal_secret]}`); `auth_nonce` is unused on this path (the authorizations are supplied, not
 * produced here). `authorizations_json` is a JSON array
 * `[{ "public_key": "<hex>", "signature": "<hex>" }, ...]`. An empty array behaves like the plain
 * single-key seal. On success `data_json` is the `EncodedPublicTransfer`.
 *
 * # Safety
 * `handle` must be a non-null, not-yet-consumed public handle. `keys_json` and `authorizations_json`
 * must be valid NUL-terminated UTF-8 C strings. The returned envelope must be freed with
 * [`ootle_result_free`]. Do **not** free `handle` afterwards — it is consumed here.
 */
OotleResult ootle_seal_and_encode_with_auth(OotlePartialTransaction *handle,
                                            const char *keys_json,
                                            const char *authorizations_json);

/**
 * Production (random-nonce) counterpart of [`ootle_seal_and_encode_with_auth`]. **Consumes** `handle`.
 * `keys_json` is `{account_secret}`. The bytes/id are not reproducible.
 *
 * # Safety
 * As [`ootle_seal_and_encode_with_auth`].
 */
OotleResult ootle_seal_and_encode_with_auth_production(OotlePartialTransaction *handle,
                                                       const char *keys_json,
                                                       const char *authorizations_json);

/**
 * Parses a raw indexer finalized-result JSON string into the typed `FinalizedResult`.
 *
 * `raw_json` is the indexer's result JSON verbatim. On success `data_json` is the `FinalizedResult`
 * serialized as JSON.
 *
 * # Safety
 * `raw_json` must be a valid NUL-terminated UTF-8 C string. The returned envelope must be freed with
 * [`ootle_result_free`].
 */
OotleResult ootle_parse_finalized_result(const char *raw_json);

/**
 * Returns the stable ABI version tag (a static NUL-terminated C string). **Do not free** the
 * returned pointer — it points at static storage, not a host-owned allocation.
 */
const char *ootle_abi_version(void);

/**
 * Frees a single heap C string previously returned by this library (e.g. an envelope field handed
 * out individually). Null-safe; call **exactly once** per string. Most callers use
 * [`ootle_result_free`] instead, which frees a whole envelope's strings.
 *
 * # Safety
 * `s` must be either null or a pointer obtained from this library and not yet freed.
 */
void ootle_string_free(char *s);

/**
 * Frees the three heap C strings owned by an [`OotleResult`] (`error_code`, `error_message`,
 * `data_json`). Null fields are skipped. Does **not** free `handle` — use
 * [`ootle_partial_transaction_free`] for that. Call **exactly once** per returned envelope.
 *
 * # Safety
 * Each non-null string field of `result` must be a pointer obtained from this library and not yet
 * freed. After this call the envelope's string fields are dangling and must not be used.
 */
void ootle_result_free(OotleResult result);

/**
 * Frees an opaque [`OotlePartialTransaction`] handle. Null-safe; call **exactly once**, and **only**
 * for a handle that was never consumed by [`ootle_apply_fetched_substates`] /
 * [`ootle_seal_and_encode`] (those take the handle by value). Freeing a consumed handle is a
 * use-after-free.
 *
 * **Kind-guarded:** if the handle is actually a stealth handle (misrouted from the `ootle_*_stealth*`
 * flow), it is **not** freed — the call is a deterministic no-op that leaves the handle intact for the
 * correct free fn ([`ootle_stealth_partial_transaction_free`]). This prevents a bad free / type
 * confusion.
 *
 * # Safety
 * `handle` must be either null or a pointer obtained from this library and not yet consumed or freed.
 */
void ootle_partial_transaction_free(OotlePartialTransaction *handle);

/**
 * One-shot deterministic stealth send: build (resolve inputs + assemble) and seal/encode in one call,
 * with every nonce/mask/seed pinned by `entropy_json`.
 *
 * Arguments (all `const char*` UTF-8 JSON unless noted):
 * - `network` — the L1 network discriminant byte.
 * - `intent_json` — a `StealthTransferIntent`.
 * - `fetched_json` — a JSON array of `FetchedSubstate`: **every** stealth-input UTXO substate, fetched up front (the
 *   wanted `utxo_<…>` ids are a pure function of each input's resource + commitment).
 * - `spend_secrets_json` — a JSON array of lowercase-hex secret scalars, one **positional** per `intent.inputs`, used
 *   to decrypt each input's spend mask.
 * - `keys_json` — `{account_secret, auth_nonce, seal_nonce}` (all lowercase hex).
 * - `entropy_json` — a `StealthEntropy` bundle (per-output + global pinned randomness).
 *
 * On success `data_json` is the `EncodedPublicTransfer` (`{encoded_transaction, transaction_id}`,
 * lowercase hex; the wire shape is shared with the public path). The bytes are deterministic for the
 * signatures this function produces; the embedded proofs are not byte-stable, so callers compare
 * *semantically* rather than byte-for-byte.
 *
 * # Safety
 * `intent_json`, `fetched_json`, `spend_secrets_json`, `keys_json`, and `entropy_json` must each be a
 * valid NUL-terminated UTF-8 C string. The returned envelope must be freed with
 * [`ootle_result_free`](crate::ootle_result_free). The secrets/entropy cross as transient hex JSON and
 * are dropped at the end of the call; the facade does not zero them.
 */
OotleResult ootle_build_and_encode_stealth_transfer(uint8_t network,
                                                    const char *intent_json,
                                                    const char *fetched_json,
                                                    const char *spend_secrets_json,
                                                    const char *keys_json,
                                                    const char *entropy_json);

/**
 * Production (random-entropy) counterpart of [`ootle_build_and_encode_stealth_transfer`]. Fills the
 * proof + seal entropy from `OsRng` internally, so there is **no** `entropy_json` argument and the
 * bytes/id are **not** reproducible (correct for real submission). `keys_json` is `{account_secret}`
 * (the seal/auth nonces are drawn from `OsRng` on this path, so the caller supplies only the secret).
 *
 * # Safety
 * As [`ootle_build_and_encode_stealth_transfer`], minus `entropy_json`.
 */
OotleResult ootle_build_and_encode_stealth_transfer_production(uint8_t network,
                                                               const char *intent_json,
                                                               const char *fetched_json,
                                                               const char *spend_secrets_json,
                                                               const char *keys_json);

/**
 * Deterministically seeds the stealth input-resolution loop, returning the opaque stealth handle (in
 * `OotleResult.handle`) **plus** the want list in `data_json` (`{"want_list":[…]}` — the serde form of
 * `WantList`'s inner `Vec<WantItem>`).
 *
 * Takes `intent_json` + `entropy_json` only — **no** up-front `fetched`/`spend_secrets` (the host
 * drives the fetch loop). The host fetches the wanted substates, then calls
 * [`ootle_apply_fetched_substates_stealth`] until it returns `{"status":"resolved"}`, at which point
 * the threaded handle wraps the assembled partial ready for [`ootle_seal_and_encode_stealth`]. The
 * pinned `entropy` is stashed in the handle so the final apply can assemble without re-passing it.
 *
 * Pass the returned handle only to the `ootle_*_stealth*` consumers /
 * [`ootle_stealth_partial_transaction_free`]. Routing it to the public-path consumers / free
 * (`ootle_apply_fetched_substates` / `ootle_seal_and_encode` / `ootle_partial_transaction_free`)
 * returns an `INVALID` error and leaves the handle intact.
 *
 * # Safety
 * `intent_json` and `entropy_json` must each be a valid NUL-terminated UTF-8 C string. The returned
 * envelope must be freed with [`ootle_result_free`](crate::ootle_result_free); the returned `handle`
 * must be consumed by [`ootle_apply_fetched_substates_stealth`] (each round) and ultimately
 * [`ootle_seal_and_encode_stealth`], or freed with [`ootle_stealth_partial_transaction_free`].
 */
OotleResult ootle_build_stealth_unsigned(uint8_t network,
                                         const char *intent_json,
                                         const char *entropy_json);

/**
 * Production (random-entropy) counterpart of [`ootle_build_stealth_unsigned`]. Fills the proof entropy
 * from `OsRng` internally (no `entropy_json`); the resulting handle's eventual bytes are **not**
 * reproducible. Returns the handle + want list; drive the loop with
 * [`ootle_apply_fetched_substates_stealth`] and seal with [`ootle_seal_and_encode_stealth_production`].
 *
 * # Safety
 * As [`ootle_build_stealth_unsigned`], minus `entropy_json`.
 */
OotleResult ootle_build_stealth_unsigned_production(uint8_t network,
                                                    const char *intent_json);

/**
 * Applies a fetched batch of substates to the stealth resolver and reports resolution status.
 *
 * **Consumes** `handle` (taken by value — treat the pointer you passed as invalid afterwards, even on
 * error), like [`ootle_apply_fetched_substates`](crate::ootle_apply_fetched_substates). `network`
 * must be the transfer's network (the handle does not carry it). `fetched_json` is a JSON array of
 * `FetchedSubstate`; `spend_secrets_json` a JSON array of lowercase-hex secret scalars (one positional
 * per `intent.inputs`). On success the envelope carries a (possibly new) handle to thread forward and
 * `data_json`:
 * - `{"status":"resolved"}` — the handle wraps the **assembled** partial; seal it via
 *   [`ootle_seal_and_encode_stealth`]; or
 * - `{"status":"need_more","fetch_ids":[…]}` — fetch the substates named in **`fetch_ids`** (the authoritative
 *   concrete next-fetch set, including ids the core discovered) and call this again on the returned handle.
 *
 * On a processing error the input handle is still consumed and freed; the returned envelope carries no
 * handle. Passing a handle that is **already** resolved (a `Ready` state) is a `STEALTH` error (the
 * handle is consumed). (Passing a *null* handle yields an `"INVALID"` envelope and consumes nothing.)
 *
 * # Safety
 * `handle` must be a non-null pointer previously returned by [`ootle_build_stealth_unsigned`] /
 * [`ootle_build_stealth_unsigned_production`] / this fn and not yet consumed. `fetched_json` and
 * `spend_secrets_json` must each be a valid NUL-terminated UTF-8 C string. The returned envelope must
 * be freed with [`ootle_result_free`](crate::ootle_result_free).
 */
OotleResult ootle_apply_fetched_substates_stealth(OotleStealthPartialTransaction *handle,
                                                  uint8_t network,
                                                  const char *fetched_json,
                                                  const char *spend_secrets_json);

/**
 * Deterministically seals + BOR-encodes a stealth partial from [`ootle_build_stealth_unsigned`].
 *
 * **Consumes** `handle` (taken by value — treat the pointer you passed as invalid afterwards, even on
 * error). `network` must be the transfer's network (the partial does not carry it; different networks
 * yield different stealth keys). `keys_json` is `{account_secret, auth_nonce, seal_nonce}`;
 * `entropy_json` supplies the stealth/ephemeral seal nonces. On success `data_json` is the
 * `EncodedPublicTransfer`. No handle is returned.
 *
 * On a processing error the input handle is still consumed and freed; the returned envelope carries no
 * handle. (Passing a *null* handle is a precondition violation that yields an `"INVALID"` envelope and
 * consumes nothing.)
 *
 * # Safety
 * `handle` must be a non-null pointer previously returned by [`ootle_build_stealth_unsigned`] and not
 * yet consumed or freed. `keys_json` and `entropy_json` must each be a valid NUL-terminated UTF-8 C
 * string. The returned envelope must be freed with [`ootle_result_free`](crate::ootle_result_free). Do
 * **not** free `handle` afterwards — it is consumed here.
 */
OotleResult ootle_seal_and_encode_stealth(OotleStealthPartialTransaction *handle,
                                          uint8_t network,
                                          const char *keys_json,
                                          const char *entropy_json);

/**
 * Production (random-entropy) counterpart of [`ootle_seal_and_encode_stealth`]. **Consumes** `handle`.
 * Takes no `entropy_json` (the seal nonces are drawn from `OsRng`); `keys_json` is `{account_secret}`
 * (the caller supplies only the secret on this path). The bytes/id are not reproducible.
 *
 * # Safety
 * As [`ootle_seal_and_encode_stealth`], minus `entropy_json`.
 */
OotleResult ootle_seal_and_encode_stealth_production(OotleStealthPartialTransaction *handle,
                                                     uint8_t network,
                                                     const char *keys_json);

/**
 * Scans an inbound stealth UTXO with a view secret and decides whether it is addressed to the scanner.
 * **Stateless — returns no handle.**
 *
 * - `network` — the L1 network discriminant byte.
 * - `scan_keys_json` — `{view_secret, account_secret?, skip_memo?}` (secrets lowercase hex; `account_secret` optional
 *   — when absent the tag + spend-condition ownership checks are skipped; `skip_memo` defaults to `false`).
 * - `inbound_output_json` — an `InboundStealthOutput` (the on-the-wire shape of a created stealth output).
 *
 * `data_json` on success is **always** a JSON object:
 * - addressed to the scanner: the `DecryptedOutput` (`{is_mine:true, value, mask, memo}`); or
 * - **not** addressed to the scanner: `{"is_mine":false}` — a *success* envelope, deliberately **not** a null
 *   `data_json` (a null payload on `ok=1` would be ambiguous for a thin host). A decrypt failing is "not mine", never
 *   an error.
 *
 * # Safety
 * `scan_keys_json` and `inbound_output_json` must each be a valid NUL-terminated UTF-8 C string. The
 * returned envelope must be freed with [`ootle_result_free`](crate::ootle_result_free). It never
 * carries a handle — do **not** call [`ootle_stealth_partial_transaction_free`] on its result.
 */
OotleResult ootle_scan_stealth_output(uint8_t network,
                                      const char *scan_keys_json,
                                      const char *inbound_output_json);

/**
 * Decodes a fetched UTXO substate (the shape the indexer returns) into the receive-shaped
 * [`InboundStealthOutput`] the scanner consumes. **Stateless — returns no handle.**
 *
 * - `substate_id_json` — the UTXO's canonical address string (`utxo_<resource>_<commitment>`), carrying the on-chain
 *   commitment + resource address the value body omits. A JSON string.
 * - `substate_value_json` — the `SubstateValue` JSON the indexer returned, verbatim (the same shape the resolver
 *   already consumes).
 *
 * On success `data_json` is the decoded [`InboundStealthOutput`] (a JSON object with hex byte
 * fields). A non-UTXO / frozen / burnt substate or a malformed nonce yields `"INVALID"` / `"KEY"`;
 * a malformed substate id or undecodable value JSON yields `"PARSE"`; a null arg yields `"INVALID"`.
 *
 * # Safety
 * `substate_id_json` and `substate_value_json` must each be a valid NUL-terminated UTF-8 C string.
 * The returned envelope must be freed with [`ootle_result_free`](crate::ootle_result_free). It never
 * carries a handle — do **not** call [`ootle_stealth_partial_transaction_free`] on its result.
 */
OotleResult ootle_decode_stealth_utxo(const char *substate_id_json,
                                      const char *substate_value_json);

/**
 * Fused **decode → scan**: decode a fetched UTXO substate and scan it with the caller's view keys in
 * one call. **Stateless — returns no handle.**
 *
 * Like [`ootle_scan_stealth_output`], this always returns a success envelope, never a null
 * `data_json`: not-mine ⇒ `{"is_mine":false}`, not an error.
 *
 * - `network` — the L1 network discriminant byte.
 * - `scan_keys_json` — `{view_secret, account_secret?, skip_memo?}` (the same bundle [`ootle_scan_stealth_output`]
 *   takes; secrets lowercase hex; `account_secret` optional — when absent the tag + spend-condition ownership checks
 *   are skipped; `skip_memo` defaults to `false`).
 * - `substate_id_json` — the UTXO's canonical address string. A JSON string.
 * - `substate_value_json` — the `SubstateValue` JSON the indexer returned, verbatim.
 *
 * `data_json` on success is **always** a JSON object: the `DecryptedOutput`
 * (`{is_mine:true, value, mask, memo}`) when addressed to the scanner, or `{"is_mine":false}` when
 * not (a *success* envelope, never null). A decrypt-miss is "not mine", never an error. A malformed
 * substate id / value yields `"PARSE"`; a non-UTXO / frozen / burnt substate yields `"INVALID"`; a
 * null arg or unknown network yields `"INVALID"`.
 *
 * # Safety
 * `scan_keys_json`, `substate_id_json`, and `substate_value_json` must each be a valid
 * NUL-terminated UTF-8 C string. The returned envelope must be freed with
 * [`ootle_result_free`](crate::ootle_result_free). It never carries a handle — do **not** call
 * [`ootle_stealth_partial_transaction_free`] on its result.
 */
OotleResult ootle_scan_stealth_substate(uint8_t network,
                                        const char *scan_keys_json,
                                        const char *substate_id_json,
                                        const char *substate_value_json);

/**
 * Decodes a sealed stealth transfer, verifies **every** signature on it, and returns its canonical
 * deterministic-field JSON (the byte-unstable proof/signature scalars nulled). **Stateless — returns
 * no handle.**
 *
 * - `network` — the L1 network discriminant byte.
 * - `sealed_encoded_transaction_hex` — the lowercase-hex `EncodedPublicTransfer::encoded_transaction` (the
 *   `TransactionEnvelope` wire form) produced by a stealth seal op.
 *
 * On success `data_json` is the decoded transaction as a JSON object with the byte-unstable set
 * `["agg_range_proof","balance_proof","signature"]` recursively nulled (signer **public keys
 * survive**). A host compares it field-for-field against the expected canonical transaction to make
 * an accept/reject decision.
 *
 * A **bad signature is an error, not a falsy success**: a tampered or otherwise invalid seal yields a
 * `"VALIDATION"` error envelope; malformed/odd-length hex yields `"PARSE"`; undecodable bytes yield
 * `"ENCODING"`; a null/invalid arg or unknown network yields `"INVALID"`.
 *
 * # Safety
 * `sealed_encoded_transaction_hex` must be a valid NUL-terminated UTF-8 C string. The returned
 * envelope must be freed with [`ootle_result_free`](crate::ootle_result_free). It never carries a
 * handle — do **not** call [`ootle_stealth_partial_transaction_free`] on its result.
 */
OotleResult ootle_validate_stealth_transfer(uint8_t network,
                                            const char *sealed_encoded_transaction_hex);

/**
 * Builds the aggregated stealth **outputs statement** for an intent's outputs deterministically (every
 * nonce/mask pinned via the supplied `entropy`), returning the statement JSON + the aggregated output
 * mask. **Stateless — returns no handle.**
 *
 * - `network` — the L1 network discriminant byte.
 * - `intent_json` — a [`StealthTransferIntent`] carrying the `outputs` (and `revealed_output_amount`).
 * - `entropy_json` — a [`StealthEntropy`] whose `per_output` slice pins every output's mask/nonces; its length
 *   **must** equal `intent.outputs.len()` (the core errors `"VALIDATION"` otherwise).
 *
 * On success `data_json` is a JSON object:
 * ```json
 * { "outputs_statement": { … }, "aggregated_output_mask": "<64-hex>" }
 * ```
 * **Semantic, not byte-stable:** the statement's aggregated bulletproof (`agg_range_proof`) is
 * byte-unstable across runs, so it is recursively **nulled** in `outputs_statement`; every other
 * statement field and the `aggregated_output_mask` (a 32-byte scalar) **are** byte-reproducible.
 *
 * Malformed `intent`/`entropy` JSON yields `"PARSE"`; a length-mismatched/invalid entropy yields
 * `"VALIDATION"`; a null arg or unknown network yields `"INVALID"`.
 *
 * # Safety
 * `intent_json` and `entropy_json` must each be a valid NUL-terminated UTF-8 C string. The returned
 * envelope must be freed with [`ootle_result_free`](crate::ootle_result_free). It never carries a
 * handle — do **not** call [`ootle_stealth_partial_transaction_free`] on its result.
 */
OotleResult ootle_build_stealth_outputs_statement(uint8_t network,
                                                  const char *intent_json,
                                                  const char *entropy_json);

/**
 * Frees an opaque [`OotleStealthPartialTransaction`] handle. Null-safe; call **exactly once**, and
 * **only** for a handle that was never consumed by [`ootle_seal_and_encode_stealth`] /
 * [`ootle_seal_and_encode_stealth_production`] (those take the handle by value). Freeing a consumed
 * handle is a use-after-free.
 *
 * **Kind-guarded:** if the handle is actually a public-path `OotlePartialTransaction` (misrouted), it
 * is **not** freed — the call is a deterministic no-op that leaves the handle intact for the correct
 * free fn ([`ootle_partial_transaction_free`](crate::ootle_partial_transaction_free)). This prevents a
 * bad free / type confusion.
 *
 * # Safety
 * `handle` must be either null or an [`OotleStealthPartialTransaction`] pointer obtained from this
 * library and not yet consumed or freed.
 */
void ootle_stealth_partial_transaction_free(OotleStealthPartialTransaction *handle);

/**
 * Decodes any fetched substate JSON into the kind-tagged
 * [`DecodedSubstate`](ootle_sdk_core::DecodedSubstate). **Stateless — returns no handle.**
 *
 * `substate_value_json` is the indexer's `SubstateValue` JSON, passed verbatim. On success
 * `data_json` is `{ "kind": "component|vault|resource|other", "value": { … } }`. For a vault the
 * `value.revealed_balance` is the revealed/unlocked amount only — the confidential side is surfaced
 * as `value.confidential_commitment_count` + `value.kind`, never a silent zero. Balances are native
 * JSON `u64`.
 *
 * A malformed/unknown substate value yields `"PARSE"`; a balance that does not fit a `u64` yields
 * `"VALIDATION"`; a null arg yields `"INVALID"`.
 *
 * # Safety
 * `substate_value_json` must be a valid NUL-terminated UTF-8 C string. The returned envelope must be
 * freed with [`ootle_result_free`](crate::ootle_result_free). It never carries a handle.
 */
OotleResult ootle_decode_substate(const char *substate_value_json);

/**
 * Computes the **revealed** balance per resource for an account. **Stateless — returns no handle.**
 *
 * `account_substate_json` is the account `Component` substate JSON; `vault_substates_json` is a JSON
 * array of [`FetchedSubstate`](ootle_sdk_core::FetchedSubstate) records (`{substate_id, version,
 * substate_value}`) — the vaults the host already fetched (the ids
 * [`ootle_account_balance_wants`] named). The core rediscovers the account's vault ids from its CBOR
 * state and matches them by id: a referenced vault not supplied is a `"RESOLUTION"` error, never a
 * silent zero.
 *
 * On success `data_json` is `{ "balances": [ { "resource_address": "resource_<hex>",
 * "revealed_balance": <u64> } ] }`. Revealed balances are native JSON `u64` and are the
 * revealed/unlocked amounts only (a confidential total requires scanning the relevant stealth UTXOs
 * separately).
 *
 * A non-component account / a non-vault entry yields `"VALIDATION"`; a missing referenced vault
 * yields `"RESOLUTION"`; a malformed substate JSON yields `"PARSE"`; a null arg yields `"INVALID"`.
 *
 * # Safety
 * `account_substate_json` and `vault_substates_json` must each be a valid NUL-terminated UTF-8 C
 * string. The returned envelope must be freed with [`ootle_result_free`](crate::ootle_result_free).
 * It never carries a handle.
 */
OotleResult ootle_account_balances(const char *account_substate_json,
                                   const char *vault_substates_json);

/**
 * Names the `vault_<hex>` ids a host should fetch to satisfy [`ootle_account_balances`] for an
 * account. **Stateless — returns no handle.**
 *
 * `account_substate_json` is the account `Component` substate JSON. On success `data_json` is
 * `{ "fetch_ids": [ "vault_<hex>", … ] }` — the same component-vault discovery
 * [`ootle_account_balances`] does, surfaced as opaque ids. The host fetches them and feeds them back
 * as `vault_substates_json`.
 *
 * A non-component account yields `"VALIDATION"`; a malformed substate JSON yields `"PARSE"`; a null
 * arg yields `"INVALID"`.
 *
 * # Safety
 * `account_substate_json` must be a valid NUL-terminated UTF-8 C string. The returned envelope must
 * be freed with [`ootle_result_free`](crate::ootle_result_free). It never carries a handle.
 */
OotleResult ootle_account_balance_wants(const char *account_substate_json);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OOTLE_SDK_H */
