// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeeCostBreakdown } from "../FeeCostBreakdown";
import type { FinalizeResult } from "../FinalizeResult";

export interface DryRunTransactionFinalizeResult {
  decision: string;
  finalize: FinalizeResult;
  fee_breakdown: FeeCostBreakdown | null;
}
