// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "../Block";

export type GetBlockResponse = {
  block: Block;
  /**
   * Total WASM metering points consumed by transactions executed for this block (the per-block budget is
   * enforced against this sum).
   */
  total_wasm_execution_points: bigint;
};
