// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ordering } from "../Ordering";

export type GetBlocksRequest = {
  limit: number;
  offset: number;
  ordering_index: number | null;
  ordering: Ordering | null;
  filter_index: number | null;
  filter: string | null;
};
