// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";

export interface GetBaseLayerEpochChangesRequest {
  start_epoch: Epoch;
  end_epoch: Epoch;
}
