// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { NodeHeight } from "../NodeHeight";
import type { Shard } from "../Shard";
import type { StateVersion } from "../StateVersion";

export type GetConsensusStatusResponse = {
  epoch: Epoch;
  height: NodeHeight;
  state: string;
  state_versions: { [key in Shard]?: StateVersion } | null;
};
