// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { NodeHeight } from "../NodeHeight";

export interface GetConsensusStatusResponse {
  epoch: Epoch;
  height: NodeHeight;
  state: string;
}
