// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticEventRecord } from "../DiagnosticEventRecord";

export type GetDiagnosticEventsResponse = {
  events: Array<DiagnosticEventRecord>;
  next_cursor: number | null;
  bounds: [number, number] | null;
};
