// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetFilteredBlocksCountRequest = { filter_index: number | null; filter: string | null };
