// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";

export type GetShardKeyRequest = { epoch: Epoch; public_key: RistrettoPublicKeyBytes };
