// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash } from "../Hash";

export type GetTemplateRequest = { template_address: Hash };
