// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VNTemplateMetadata } from "./VNTemplateMetadata";

export type GetTemplatesResponse = { templates: Array<VNTemplateMetadata> };
