// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateAbi } from "./TemplateAbi";
import type { TemplateMetadata } from "./TemplateMetadata";

export type GetTemplateResponse = { registration_metadata: TemplateMetadata; abi: TemplateAbi };
