// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListBlocksRequest = {
  /**
   * If provided, `limit` blocks from the specified block back will be returned. Otherwise `limit` blocks from the
   * leaf block will be provided.
   */
  from_id: string | null;
  limit: number;
};
