// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash } from "../Hash";

export type TemplateMetadata = {
  name: string;
  address: Hash;
  /**
   * SHA hash of binary
   */
  binary_sha: Array<number>;
};
