// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";
import type { SubstateAddress } from "../SubstateAddress";

export type ValidatorNode = {
  address: string;
  public_key: RistrettoPublicKeyBytes;
  shard_key: SubstateAddress;
  start_epoch: Epoch;
  fee_claim_public_key: RistrettoPublicKeyBytes;
};
