// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArgDef } from "../ArgDef";

export type VNFunctionDef = { name: string; arguments: Array<ArgDef>; output: string; is_mut: boolean };
