// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseLayerValidatorNode } from "../base-node-client/BaseLayerValidatorNode";

export type VNGetAllVnsResponse = { vns: Array<BaseLayerValidatorNode> };
