// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "../Decision";
import type { TransactionExecution } from "../TransactionExecution";

export interface VNGetTransactionResultResponse {
  transaction_execution: TransactionExecution;
  final_decision: Decision;
  finalize_at: string;
}
