// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";

export type VNGetIdentityResponse = {
  peer_id: string;
  public_key: RistrettoPublicKeyBytes;
  public_addresses: Array<string>;
  supported_protocols: Array<string>;
  protocol_version: string;
  user_agent: string;
};
