// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateValue } from "../SubstateValue";
import type { SubstateStatus } from "./SubstateStatus";

export type VNGetSubstateResponse = { value: SubstateValue | null; status: SubstateStatus };
