// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VNLogLevel } from "./VNLogLevel";

export type VNLogEntry = { timestamp: number; message: string; level: VNLogLevel };
