// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transaction } from "../Transaction";

/**
 * A request to submit a transaction
 */
export type VNSubmitTransactionRequest = { transaction: Transaction };
