// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionId } from "../TransactionId";
import type { DryRunTransactionFinalizeResult } from "./DryRunTransactionFinalizeResult";

export type VNSubmitTransactionResponse = {
  transaction_id: TransactionId;
  /**
   * The result is a _dry run_ transaction.
   */
  dry_run_result: DryRunTransactionFinalizeResult | null;
};
