// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash } from "../Hash";
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";

export type VNTemplateMetadata = { name: string; address: Hash; code_size: number; author: RistrettoPublicKeyBytes };
