global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: "/_metrics"
    static_configs:
      # Configure prometheus to scrape http://localhost:{my_json_rpc_port}/_metrics. By default the VN's JSON-RPC server listens on port 18200.
      - targets: [ 'host.docker.internal:12005' ]

      #- job_name: 'node'
      #static_configs:
      #- targets: ['node-exporter:9100']

remote_write:
  #  - url: 'http://host.docker.internal:3000'
  - url: 'http://grafana:3000'
    basic_auth:
      username: 'admin'
      password: 'admin'
