//   Copyright 2025 The Tari Project
//   SPDX-License-Identifier: BSD-3-Clause

import { describe, expect, it } from "vitest";
import { DecodedOotleAddress, encodeOotleAddress, decodeOotleAddress } from "../src";

describe("OotleAddress de/encoding", () => {
  function makeDecodedAddress() {
    return {
      network: "igor",
      accountPublicKey: "a1b2c3d4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef0",
      viewOnlyKey: "0fedcba9876543210fedcba9876543210fedcba9876543210fedcba98765432a",
    } as DecodedOotleAddress;
  }

  it("encodes and decodes a valid address", () => {
    const sample = makeDecodedAddress();

    const address = encodeOotleAddress(sample);

    let parsed: DecodedOotleAddress;
    expect(() => {
      parsed = decodeOotleAddress(address);
    }).not.toThrow();

    expect(parsed.network).toEqual(sample.network);
    expect(parsed.viewOnlyKey).toEqual(sample.viewOnlyKey);
    expect(parsed.accountPublicKey).toEqual(sample.accountPublicKey);
  });

  it("encodes and decodes address with payRef", () => {
    const sample = makeDecodedAddress();
    const payRefString = "Invoice #12345";
    const check = encodeOotleAddress(sample);
    sample.payRef = payRefString;

    const address = encodeOotleAddress(sample);

    expect(address).not.toEqual(check);

    let parsed: DecodedOotleAddress;
    expect(() => {
      parsed = decodeOotleAddress(address);
    }).not.toThrow();

    expect(parsed.network).toEqual(sample.network);
    expect(parsed.viewOnlyKey).toEqual(sample.viewOnlyKey);
    expect(parsed.accountPublicKey).toEqual(sample.accountPublicKey);
    expect(parsed.payRef).toEqual(payRefString);
  });

  it("throws on invalid address", () => {
    expect(() => decodeOotleAddress("invalidAddress")).toThrow();
  });

  it("throws on invalid public key hex length", () => {
    let sample1 = makeDecodedAddress();
    sample1.accountPublicKey += "deadbeaf";
    expect(() => encodeOotleAddress(sample1)).toThrow();

    let sample2 = makeDecodedAddress();
    sample2.accountPublicKey = sample2.accountPublicKey.slice(1);
    expect(() => encodeOotleAddress(sample2)).toThrow();
  });

  it("throws if address is tampered", () => {
    const sample = makeDecodedAddress();
    const address = encodeOotleAddress(sample);
    // Tamper with the address by changing a character
    const tamperedAddress = address.slice(0, -1) + (address.slice(-1) === "a" ? "b" : "a");
    expect(() => decodeOotleAddress(tamperedAddress)).toThrow();
  });

  it("decodes a known address correctly", () => {
    // This address was generated by the rust version of OotleAddress
    let s =
      "xtr_loc_1ffs0tmejptxzujfnp4f6r44md2cnr9p9d9ayphcmkjxfmmapf3g9cghy8dlpnlwtc04t2jyk6kaz6a9eh2zww9flsl73ydue3qmwyuq5djpu2";
    let r = decodeOotleAddress(s);
    expect(r.network).toEqual("localnet");
    expect(r.accountPublicKey).toEqual("4a60f5ef320acc2e49330d53a1d6bb6ab1319425697a40df1bb48c9defa14c50");
    expect(r.viewOnlyKey).toEqual("5c22e43b7e19fdcbc3eab54896d5ba2d74b9ba84e7153f87fd1237998836e270");
  });

  it("throws on unsupported network prefix", () => {
    const sample = makeDecodedAddress();
    // Temporarily change network to an unsupported one
    (sample as any).network = "unsupportednet";
    expect(() => encodeOotleAddress(sample)).toThrow();
  });
});
