// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StealthTransferStatement } from "../StealthTransferStatement";
import type { KeyId } from "./KeyId";
import type { StealthUtxoSpendKeyId } from "./StealthUtxoSpendKeyId";

export type AccountsCreateStealthTransferStatementResponse = {
  statements: Array<StealthTransferStatement>;
  lock_id: number;
  signing_keys: Array<KeyId>;
  /**
   * Any signatures using a stealth spend key required to spend inputs provided in the statements.
   */
  utxo_signers: Array<StealthUtxoSpendKeyId>;
};
