// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddressOrName } from "./ComponentAddressOrName";
import type { KeyId } from "./KeyId";

export type AccountOrKeyId = { "Account": ComponentAddressOrName | null } | { "KeyId": KeyId };
