// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "../ResourceAddress";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export type AccountsAssociateStealthResourceRequest = {
  account: ComponentAddressOrName;
  resource_address: ResourceAddress;
};
