// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "../ResourceAddress";
import type { TransactionId } from "../TransactionId";
import type { BalanceChangeSourceType } from "./BalanceChangeSourceType";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export type AccountsGetBalanceChangesRequest = {
  account: ComponentAddressOrName;
  offset: number;
  limit: number;
  resource_address: ResourceAddress | null;
  transaction_id: TransactionId | null;
  source_type: BalanceChangeSourceType | null;
};
