// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddress } from "../ComponentAddress";
import type { BalanceEntry } from "./BalanceEntry";

export type AccountsGetBalancesResponse = { address: ComponentAddress, balances: Array<BalanceEntry>, };
