// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceChange } from "./BalanceChange";

export type AccountsGetBalanceChangesResponse = { changes: Array<BalanceChange>; total: bigint };
