// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { ResourceAddress } from "../ResourceAddress";
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export type AccountsTransferRequest = { account: ComponentAddressOrName | null, amount: Amount, resource_address: ResourceAddress, destination_public_key: RistrettoPublicKeyBytes, max_fee: bigint, proof_from_badge_resource: ResourceAddress | null, dry_run: boolean, };
