// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export type AccountsCreateFreeTestCoinsRequest = { account: ComponentAddressOrName, max_fee: bigint, };
