// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransferStatementRequest } from "./TransferStatementRequest";

export type AccountsCreateStealthTransferStatementRequest = { requests: Array<TransferStatementRequest>, };
