// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export type AccountsCreateFreeTestCoinsRequest = {
  account: ComponentAddressOrName;
  amount: Amount;
  max_fee: number | null;
};
