// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AddressBookEntry {
  id: number;
  name: string;
  address: string;
  memo: string | null;
}
