// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressBookEntry } from "./AddressBookEntry";

export type AddressBookListResponse = { entries: Array<AddressBookEntry> };
