// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JrpcPermission } from "../JrpcPermission";

/**
 * Metadata returned by `auth.list_api_keys`. Mirrors the storage row
 * minus the hash (not needed by the admin) and the raw key (not stored
 * anywhere persistent after creation).
 */
export type ApiKeyInfo = {
  id: number;
  name: string;
  permissions: Array<JrpcPermission>;
  /** Unix timestamp (seconds). */
  created_at: bigint;
  /** Unix timestamp (seconds). `null` if never used since creation. */
  last_used_at: bigint | null;
  /** Unix timestamp (seconds). `null` for active keys. */
  revoked_at: bigint | null;
  /** Optional hard expiry (unix seconds). `null` = no expiry. */
  expires_at: bigint | null;
};
