// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebauthnFinishAuthRequest } from "./WebauthnFinishAuthRequest";

/**
 * Credentials for the `auth.request` JSON-RPC entry point. Used by humans
 * authenticating via WebAuthN (or in `none` auth mode); agent automation
 * authenticates by sending the raw API key as the `Authorization: Bearer
 * …` header on every JSON-RPC call instead, with no `auth.request`
 * round-trip.
 */
export type AuthCredentials = "None" | { WebAuthN: WebauthnFinishAuthRequest };
