// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JrpcPermission } from "../JrpcPermission";

/**
 * Daemon → admin: response after successful key creation.
 *
 * `key` is the RAW key material and is included EXACTLY ONCE.
 * The daemon only persists a SHA-256 hash; a database leak does not
 * expose this string. The UI must store it immediately.
 */
export type AuthCreateApiKeyResponse = {
  id: number;
  name: string;
  permissions: Array<JrpcPermission>;
  /** The raw `twda_…` key. Shown once; not stored by the daemon. */
  key: string;
  /** Unix timestamp (seconds) of creation. */
  created_at: bigint;
};
