// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permission } from "../Permission";
import type { RefreshTokenHash } from "./RefreshTokenHash";

export type AuthSessionInfo = { id: RefreshTokenHash, permissions: Array<Permission>, exp: bigint, };
