// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebauthnFinishAuthRequest } from "./WebauthnFinishAuthRequest";

export type AuthCredentials = "None" | { WebAuthN: WebauthnFinishAuthRequest };
