// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Admin → daemon: list all API keys, active and revoked. The raw key
 * material is NEVER included in the response.
 */
export type AuthListApiKeysRequest = Record<string, never>;
