// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefreshTokenHash } from "./RefreshTokenHash";

export type AuthRevokeTokenRequest = { refresh_token_id: RefreshTokenHash, };
