// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKeyInfo } from "./ApiKeyInfo";

export type AuthListApiKeysResponse = { keys: Array<ApiKeyInfo> };
