// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permission } from "../Permission";

/**
 * Daemon → admin: response after successful key creation.
 *
 * `api_key` is the RAW key material and is included in this response
 * EXACTLY ONCE; it cannot be retrieved again. The admin/UI must store it
 * immediately (clipboard / secrets manager). The daemon only persists a
 * SHA-256 hash, so a database leak does not expose this string.
 */
export type AuthCreateApiKeyResponse = {
  id: number;
  name: string;
  permissions: Array<Permission>;
  api_key: string;
  /**
   * Unix timestamp (seconds) of creation.
   */
  created_at: bigint;
};
