// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JrpcPermission } from "../JrpcPermission";
import type { AuthCredentials } from "./AuthCredentials";

export type AuthLoginRequest = { permissions: Array<JrpcPermission>; credentials: AuthCredentials };
