// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthApiKeyInfo } from "./AuthApiKeyInfo";

export type AuthListApiKeysResponse = { api_keys: Array<AuthApiKeyInfo> };
