// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JrpcPermission } from "../JrpcPermission";
import type { RefreshTokenHash } from "./RefreshTokenHash";

export type AuthSessionInfo = { id: RefreshTokenHash; permissions: Array<JrpcPermission>; exp: bigint };
