// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Admin → daemon: revoke an API key by its id. The row is soft-deleted
 * (`revoked_at` stamped) so admin tooling can still see the historical
 * `last_used_at` of revoked credentials, but the storage layer filters
 * revoked rows out of authentication lookups so revocation takes effect
 * immediately.
 */
export type AuthRevokeApiKeyRequest = { id: number, };
