// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthSessionInfo } from "./AuthSessionInfo";

export type AuthListSessionsResponse = { sessions: Array<AuthSessionInfo>, };
