// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JrpcPermission } from "../JrpcPermission";

export type AuthCreateApiKeyRequest = {
  name: string;
  permissions: Array<JrpcPermission>;
  confirm_admin: boolean;
};
