// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Admin → daemon: list API keys. By default returns only non-revoked
 * rows (the typical admin-UI view); set `include_revoked` to retrieve
 * the historical audit list. Expired keys are always included — their
 * `last_used_at` is useful audit context. The raw key material is
 * NEVER included in the response.
 */
export type AuthListApiKeysRequest = { include_revoked: boolean };
