// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionDef } from "../FunctionDef";
import type { Hash32 } from "../Hash32";
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";

export type AuthoredTemplate = { author_public_key: RistrettoPublicKeyBytes, address: Hash32, name: string, abi_version: number, functions: Array<FunctionDef>, };
