// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { NonFungibleAddress } from "../NonFungibleAddress";
import type { ResourceAddress } from "../ResourceAddress";

export type BadgeUsage =
  | "None"
  | { Resource: ResourceAddress }
  | { NonFungible: NonFungibleAddress }
  | { AmountOfResource: { resource: ResourceAddress; amount: Amount } };
