// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BalanceChangeSource =
  | { type: "transaction"; transaction_id: string }
  | { type: "scan" }
  | { type: "recovery" };
