// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BalanceChangeSource =
  | { type: "Transaction"; transaction_id: string }
  | { type: "Scan" }
  | { type: "Recovery" };
