// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceChangeSource } from "./BalanceChangeSource";

export type BalanceChangeEntry = {
  vault_address: string;
  resource_address: string;
  before_revealed_balance: string;
  after_revealed_balance: string;
  before_confidential_balance: string;
  after_confidential_balance: string;
  revealed_delta: string;
  confidential_delta: string;
  source: BalanceChangeSource;
  transaction_id: string | null;
  created_at: string;
};
