// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { ComponentAddress } from "../ComponentAddress";
import type { ResourceAddress } from "../ResourceAddress";
import type { VaultId } from "../VaultId";
import type { BalanceChangeSource } from "./BalanceChangeSource";

export type BalanceChange = {
  id: number;
  account_address: ComponentAddress;
  vault_address: VaultId;
  resource_address: ResourceAddress;
  token_symbol: string | null;
  divisibility: number;
  revealed_before: Amount;
  revealed_after: Amount;
  confidential_before: Amount;
  confidential_after: Amount;
  revealed_delta: string;
  confidential_delta: string;
  source: BalanceChangeSource;
  transaction_id: string | null;
  created_at: string;
};
