// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BurnProofsListRequest = {
  /**
   * Optional filter by account public key. Only proofs whose file name starts with this key
   * will be returned. Proofs with file names that do not match the expected
   * `{public_key}_{commitment}.json` format are always included.
   */
  filter_by_public_key: string | null;
};
