// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BurnProofFileInfo } from "./BurnProofFileInfo";

export type BurnProofsListResponse = { proofs: Array<BurnProofFileInfo> };
