// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaimBurnProof } from "./ClaimBurnProof";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export type ClaimBurnRequest = { account: ComponentAddressOrName, claim_proof: ClaimBurnProof, max_fee: bigint, is_dry_run: boolean, };
