// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaimBurnProofContents } from "./ClaimBurnProofContents";

export type ClaimBurnProof = { "Contents": ClaimBurnProofContents } | { "FromFile": { file_name: string, } };
