// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptedData } from "../EncryptedData";
import type { MinotariBurnClaimProof } from "../MinotariBurnClaimProof";

export type ClaimBurnProofContents = { claim_proof: MinotariBurnClaimProof; encrypted_data: EncryptedData };
