// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { ConfidentialOutputAddress } from "../ConfidentialOutputAddress";
import type { Memo } from "../Memo";
import type { OutputStatus } from "../OutputStatus";
import type { VaultId } from "../VaultId";

export type ConfidentialOutputInfo = {
  /**
   * Address of the output's own substate. It carries the commitment, which is the output's identity.
   */
  address: ConfidentialOutputAddress;
  /**
   * The vault holding this output. Membership of a vault's commitment list is what authorises the spend.
   */
  vault_id: VaultId;
  /**
   * The decrypted value. Zero for an output the wallet could not decrypt (`OutputStatus::Invalid`).
   */
  value: Amount;
  status: OutputStatus;
  memo: Memo | null;
};
