// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueScanCoverage } from "./ValueScanCoverage";

export type ConfidentialViewVaultBalanceResponse = {
  balances: Record<string, number | null>;
  searched: ValueScanCoverage;
};
