// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfidentialOutputInfo } from "./ConfidentialOutputInfo";

export type ConfidentialOutputsListResponse = { outputs: Array<ConfidentialOutputInfo> };
