// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { Memo } from "../Memo";
import type { OotleAddress } from "../OotleAddress";
import type { ResourceAddress } from "../ResourceAddress";
import type { UtxoInputSelection } from "../UtxoInputSelection";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export type ConfidentialTransferRequest = { account: ComponentAddressOrName | null, amount: Amount, input_selection: UtxoInputSelection, resource_address: ResourceAddress, destination_address: OotleAddress, max_fee: bigint, output_to_revealed: boolean, proof_from_badge_resource: ResourceAddress | null, memo?: Memo | null, dry_run: boolean, };
