// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a caller sees for a request: its stored status, or `Expired` when the
 * approval window has closed on a request that never reached a terminal state.
 */
export type EffectiveStatus = "Pending" | "Approved" | "Rejected" | "Submitting" | "Submitted" | "Expired";
