// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceChangeSource } from "./BalanceChangeSource";
import type { ResourceAddress } from "../ResourceAddress";

export type GetBalanceChangesRequest = {
  account: ComponentAddressOrName | null;
  offset: number | null;
  limit: number | null;
  resource_address: ResourceAddress | null;
  transaction_id: string | null;
  source_type: BalanceChangeSourceType | null;
  start_time: string | null;
  end_time: string | null;
};