// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceChangeEntry } from "./BalanceChangeEntry";

export type GetBalanceChangesResponse = {
  changes: Array<BalanceChangeEntry>;
  total: bigint;
};
