// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddressOrName } from "./ComponentAddressOrName";
import type { ResourceAddress } from "../ResourceAddress";

export type GetBalanceChangesRequest = {
  account: ComponentAddressOrName | null;
  offset: number | null;
  limit: number | null;
  resource_address: ResourceAddress | null;
  transaction_id: string | null;
};
