// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonFungibleId } from "../NonFungibleId";
import type { ResourceAddress } from "../ResourceAddress";

export type GetNftRequest = { resource_address: ResourceAddress; nft_id: NonFungibleId };
