// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shard } from "../Shard";
import type { FeePoolDetails } from "./FeePoolDetails";

export type GetValidatorFeesResponse = { fees: { [key in Shard]?: FeePoolDetails } };
