// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { UtxoAddress } from "../UtxoAddress";
import type { UtxoInputSelection } from "../UtxoInputSelection";

export type InputSelection = { "FromBucket": { revealed_amount: Amount, } } | { "Selection": UtxoInputSelection } | { "Specific": { utxo_addresses: Array<UtxoAddress>, } };
