// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyBranch } from "./KeyBranch";

export type KeyId = { "Derived": { key_branch: KeyBranch, index: bigint, } } | { "Imported": { local_key_id: bigint, } };
