// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyType } from "./KeyType";

/**
 * Imports an externally-generated secret key into the wallet's keystore. The `secret_key` is transmitted as hex.
 */
export type KeysImportRequest = { secret_key: string; key_type: KeyType };
