// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export type MintFaucetNftRequest = { account: ComponentAddressOrName, mutable_data: object, number_to_mint: bigint, max_fee: bigint | null, };
