// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { ComponentAddress } from "../ComponentAddress";
import type { ResourceAddress } from "../ResourceAddress";

export type PayFeeWithSwapParams = { pool_address: ComponentAddress, input_resource: ResourceAddress, input_amount: Amount, min_xtr_output_amount: Amount, };
