// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessRule } from "../AccessRule";
import type { SpendCondition } from "../SpendCondition";
import type { TemplateFunction } from "../TemplateFunction";

/**
 * How a created stealth output is gated for spending (TIP-0006). `StealthPublicKey` produces a key-path output (a
 * `spend_key`); the other variants produce a condition tree (a `condition_root`). `AccessRule`/`TemplateFunction` are
 * single-leaf conveniences; `Conditions` commits a full multi-leaf tree (a MAST of alternative spend paths).
 */
export type PayTo =
  | "StealthPublicKey"
  | { AccessRule: AccessRule }
  | { TemplateFunction: TemplateFunction }
  | { Conditions: Array<SpendCondition> };
