// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessRule } from "../AccessRule";
import type { SpendScript } from "../SpendScript";

export type PayTo = "StealthPublicKey" | { AccessRule: AccessRule } | { Script: SpendScript };
