// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfidentialWithdrawProof } from "../ConfidentialWithdrawProof";

export type ProofsGenerateResponse = { proof_id: number; proof: ConfidentialWithdrawProof };
