// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { Memo } from "../Memo";
import type { OotleAddress } from "../OotleAddress";
import type { ResourceAddress } from "../ResourceAddress";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export type ProofsGenerateRequest = {
  confidential_amount: Amount;
  reveal_amount: Amount;
  account: ComponentAddressOrName | null;
  resource_address: ResourceAddress;
  destination_address: OotleAddress;
  output_memo?: Memo | null;
};
