// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Template metadata input for publishing. Either provide the raw metadata for server-side hashing,
 * or a pre-computed hash.
 */
export type PublishTemplateMetadata =
  | { type: "Json"; data: string }
  | { type: "Cbor"; data: string }
  | { type: "Hash"; data: string };
