// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export type PublishTemplateRequest = {
  binary: string;
  fee_account: ComponentAddressOrName | null;
  max_fee: number;
  /**
   * Attempt to infer inputs and their dependencies from instructions. If false, the provided transaction must
   * contain the required inputs.
   */
  detect_inputs: boolean;
  dry_run: boolean;
  /**
   * Optional multihash of off-chain CBOR metadata
   */
  metadata_hash?: string | null;
};
