// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resource } from "../Resource";
import type { ResourceAddress } from "../ResourceAddress";

export type ResourcesGetManyResponse = {
  /**
   * The requested resources this wallet has stored. An address the wallet has no record of is
   * absent from the map.
   */
  resources: { [key in ResourceAddress]?: Resource };
};
