// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "../ResourceAddress";

export type ResourcesGetManyRequest = { addresses: Array<ResourceAddress> };
