// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SigningRequestInfo } from "./SigningRequestInfo";

export type SigningRequestGetResponse = { request: SigningRequestInfo };
