// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyId } from "./KeyId";
import type { TemplateMetadata } from "../TemplateMetadata/TemplateMetadata";

export type SignTemplateMetadataRequest = {
  key_id: KeyId;
  template_address: string;
  /**
   * The template metadata to sign. Provided as an inline JSON object.
   */
  metadata: TemplateMetadata;
};
