// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionSignature } from "../TransactionSignature";
import type { SigningRequestEffectiveStatus } from "./SigningRequestEffectiveStatus";

export type SigningRequestDecisionResponse = {
  request_id: number;
  status: SigningRequestEffectiveStatus;
  /**
   * Present when the request was approved.
   */
  signature: TransactionSignature | null;
};
