// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";
import type { UnsignedTransaction } from "../UnsignedTransaction";
import type { KeyId } from "./KeyId";

/**
 * Ask this wallet to co-sign a transaction that someone else seals.
 *
 * A person approves the request in the wallet UI; walletd then signs and
 * stores the [`TransactionSignature`] for the requester to fetch with
 * `signing_requests.get` and submit as part of the sealed transaction.
 */
export type SigningRequestCreateRequest = {
  /**
   * The complete transaction body. Every field is covered by the signature,
   * so it must be final: inputs resolved, fee instructions and epochs set.
   */
  transaction: UnsignedTransaction;
  /**
   * Public key of the party that will seal the transaction. The signature
   * commits to it.
   */
  seal_public_key: RistrettoPublicKeyBytes;
  /**
   * The wallet key to sign with.
   */
  key_id: KeyId;
  /**
   * Free text shown to the approver, labelled as coming from the requester.
   */
  memo: string;
  /**
   * How long a person has to approve, in seconds. Defaults to the daemon's
   * `signing_request_ttl` (one day unless configured).
   */
  ttl_secs: number | null;
};
