// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SigningRequestEffectiveStatus } from "./SigningRequestEffectiveStatus";

export type SigningRequestListRequest = {
  /**
   * Only return requests whose effective status matches.
   */
  status: SigningRequestEffectiveStatus | null;
};
