// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SignTemplateMetadataResponse = {
  public_nonce: string;
  signature: string;
  public_key: string;
  /**
   * Hex-encoded canonical CBOR of the metadata (the signed payload).
   */
  metadata_cbor: string;
  /**
   * The metadata hash derived from the CBOR encoding.
   */
  metadata_hash: string;
};
