// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SigningRequestCreateResponse = {
  request_id: number;
  /**
   * The authorization message the signature will sign, hex encoded. Its
   * leading bytes serve as a fingerprint the approver can compare out of
   * band.
   */
  message_hash: string;
  /**
   * Unix timestamp (seconds).
   */
  expires_at: bigint;
};
