// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";
import type { TransactionSignature } from "../TransactionSignature";
import type { UnsignedTransaction } from "../UnsignedTransaction";
import type { KeyId } from "./KeyId";
import type { SigningRequestEffectiveStatus } from "./SigningRequestEffectiveStatus";
import type { SigningRequester } from "./SigningRequester";

export type SigningRequestInfo = {
  request_id: number;
  /**
   * The transaction body the signature commits to.
   */
  transaction: UnsignedTransaction;
  seal_public_key: RistrettoPublicKeyBytes;
  key_id: KeyId;
  /**
   * Public key of `key_id`.
   */
  signer_public_key: RistrettoPublicKeyBytes;
  /**
   * The authorization message the signature signs, hex encoded.
   */
  message_hash: string;
  /**
   * Requester-supplied text. Display only; nothing verifies it.
   */
  memo: string;
  /**
   * Who created the request. Display only.
   */
  requester: SigningRequester;
  status: SigningRequestEffectiveStatus;
  /**
   * Present once the request is `Signed`.
   */
  signature: TransactionSignature | null;
  /**
   * Unix timestamp (seconds).
   */
  expires_at: bigint;
  /**
   * Unix timestamp (seconds) of approval or rejection.
   */
  decided_at: bigint | null;
  /**
   * Unix timestamp (seconds).
   */
  created_at: bigint;
};
