// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who created a signing request, as the wallet authenticated it.
 */
export type SigningRequester = "WalletSession" | { ApiKey: { name: string } } | "ConnectedApp";
