// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a caller sees for a signing request: its stored status, or `Expired`
 * when the approval window closed while it was still pending.
 */
export type SigningRequestEffectiveStatus = "Pending" | "Signed" | "Rejected" | "Expired";
