// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UtxoId } from "../UtxoId";
import type { ValueScanCoverage } from "./ValueScanCoverage";

export type StealthUtxosDecryptValueResponse = {
  values: { [key in UtxoId]?: bigint | null };
  searched: ValueScanCoverage;
};
