// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "../ResourceAddress";
import type { UtxoId } from "../UtxoId";

export type StealthUtxosDecryptValueRequest = {
  resource_address: ResourceAddress;
  ids: Array<UtxoId>;
  view_key_id: bigint;
  minimum_expected_value: bigint | null;
  maximum_expected_value: bigint;
};
