// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddress } from "../ComponentAddress";
import type { OutputStatus } from "../OutputStatus";
import type { ResourceAddress } from "../ResourceAddress";

export type StealthUtxosListRequest = { resource_address: ResourceAddress, account_address: ComponentAddress | null, filter_by_status: OutputStatus | null, };
