// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { Memo } from "../Memo";
import type { OotleAddress } from "../OotleAddress";
import type { PayTo } from "./PayTo";

export type StealthTransfer = { destination_address: OotleAddress, blinded_output_amount: number | bigint | string, revealed_output_amount: Amount, output_memo?: Memo | null, pay_to: PayTo, };
