// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "../ResourceAddress";
import type { UtxoInputSelection } from "../UtxoInputSelection";
import type { BadgeUsage } from "./BadgeUsage";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";
import type { StealthTransfer } from "./StealthTransfer";
import type { TransferFeeParams } from "./TransferFeeParams";

export type StealthTransferRequest = {
  owner_account: ComponentAddressOrName;
  fee_params: TransferFeeParams;
  input_selection: UtxoInputSelection;
  resource_address: ResourceAddress;
  badge_usage?: BadgeUsage;
  transfers: Array<StealthTransfer>;
  max_fee: bigint;
  dry_run: boolean;
};
