// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { Memo } from "../Memo";
import type { OotleAddress } from "../OotleAddress";
import type { PayTo } from "./PayTo";

export type StealthTransfer = {
  destination_address: OotleAddress;
  blinded_output_amount: number | bigint | string;
  revealed_output_amount: Amount;
  output_memo?: Memo | null;
  pay_to: PayTo;
  /**
   * If set, the sender's Ootle address is attached as the output memo so the recipient can identify and save
   * the sender as a contact. Mutually exclusive with `output_memo` (the sender address takes precedence).
   */
  attach_sender_address: boolean;
  /**
   * Optional pay reference (UTF-8) to embed inside the sender-address memo when `attach_sender_address` is
   * true. Use this to forward the destination's expected pay reference so it isn't silently dropped. Maximum
   * 64 bytes; longer values are rejected with an `invalid_params` error. If unset, the sender account's own
   * pay reference is used (if any).
   */
  sender_address_pay_ref?: string | null;
};
