// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Substate } from "../Substate";
import type { WalletSubstateInfo } from "./WalletSubstateInfo";

export type SubstatesGetResponse = { local_record: WalletSubstateInfo | null, substate_from_remote: Substate | null, };
