// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SwapPoolsListRequest = { 
/**
 * Filter pools to only those containing this exact resource pair (in any order).
 * Both must be provided for filtering to take effect.
 */
resource_pair: [string, string] | null, limit: bigint | null, offset: bigint | null, };
