// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";

export type SwapPoolGetExchangeRateRequest = { pool_address: string, 
/**
 * If provided, the response will include the calculated swap input amount needed
 * to receive at least this amount of TARI from the pool (with a slippage margin).
 */
desired_tari_output: Amount | null, };
