// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";

export type SwapPoolInfo = { pool_address: string, resource_a: string, balance_a: Amount, resource_b: string, balance_b: Amount, };
