// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SwapPoolInfo } from "./SwapPoolInfo";

export type SwapPoolsListResponse = { pools: Array<SwapPoolInfo>, };
