// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";

export type SwapPoolGetExchangeRateRequest = {
  pool_address: string;
  desired_tari_output?: Amount | null;
};
