// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";

export type TemplatesListAuthoredRequest = {
  author_public_key: RistrettoPublicKeyBytes | null;
  page: number;
  page_size: number;
};
