// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthoredTemplate } from "./AuthoredTemplate";

export type TemplatesListAuthoredResponse = { templates: Array<AuthoredTemplate>, total_templates: bigint, };
