// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinalizeResult } from "../FinalizeResult";
import type { TransactionId } from "../TransactionId";
import type { TransactionStatus } from "../TransactionStatus";

export type TransactionWaitResultResponse = {
  transaction_id: TransactionId;
  result: FinalizeResult | null;
  status: TransactionStatus;
  final_fee: number;
  timed_out: boolean;
};
