// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionId } from "../TransactionId";
import type { UnsignedTransaction } from "../UnsignedTransaction";
import type { EffectiveStatus } from "./EffectiveStatus";
import type { KeyId } from "./KeyId";
import type { TransactionRequestValueSummary } from "./TransactionRequestValueSummary";

export type TransactionRequestInfo = {
  request_id: number;
  /**
   * The frozen transaction, decoded for display. These are the exact bytes
   * an approval commits to.
   */
  transaction: UnsignedTransaction;
  seal_signer: KeyId;
  other_signers: Array<KeyId>;
  /**
   * Admin-assigned name of the API key that created this request, or `None`
   * for a wallet session. Display only -- nothing authorises on it.
   */
  requested_by: string | null;
  status: EffectiveStatus;
  transaction_id: TransactionId | null;
  /**
   * `None` for an ordinary transaction, whose instructions are readable.
   */
  value_summary: TransactionRequestValueSummary | null;
  /**
   * Unix timestamp (seconds).
   */
  expires_at: bigint;
  /**
   * Unix timestamp (seconds). `None` until approved.
   */
  approved_at: bigint | null;
  /**
   * Unix timestamp (seconds).
   */
  created_at: bigint;
};
