// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonFungibleId } from "../NonFungibleId";
import type { OotleAddress } from "../OotleAddress";
import type { ResourceAddress } from "../ResourceAddress";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export type TransferNftRequest = {
  resource_address: ResourceAddress;
  nfts: Array<NonFungibleId>;
  fee_payer_account: ComponentAddressOrName;
  source_account: ComponentAddressOrName;
  target_account_address: OotleAddress;
  max_fee: bigint;
  dry_run: boolean;
};
