// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "../ResourceAddress";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";
import type { InputSelection } from "./InputSelection";
import type { TransferOutput } from "./TransferOutput";

export type TransferStatementRequest = { sender_account: ComponentAddressOrName, resource_address: ResourceAddress, input_selection: InputSelection, outputs: Array<TransferOutput>, };
