// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnsignedTransaction } from "../UnsignedTransaction";

export type TransactionDetectInputsRequest = {
  transaction: UnsignedTransaction;
  /**
   * If true (default), detected inputs omit versions so consensus resolves
   * them; if false, walletd pins the versions it currently knows.
   */
  use_unversioned: boolean;
};
