// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecuteResult } from "../ExecuteResult";
import type { TransactionId } from "../TransactionId";

export type TransactionSubmitManifestResponse = {
  transaction_id: TransactionId;
  /**
   * The minimum fee required to submit this transaction. Only present for dry runs.
   * Includes a +1 buffer over `total_fees_charged` to account for storage fee rounding
   * differences between the dry run and actual submission.
   */
  required_fees: number | null;
  result: ExecuteResult | null;
};
