// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnsignedTransaction } from "../UnsignedTransaction";

export type TransactionDetectInputsResponse = {
  /**
   * The input transaction with the detected inputs merged in.
   */
  transaction: UnsignedTransaction;
};
