// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UtxoInputSelection } from "../UtxoInputSelection";
import type { PayFeeWithSwapParams } from "./PayFeeWithSwapParams";

export type TransferFeeParams = { input_selection: UtxoInputSelection; pay_fee_with_swap: PayFeeWithSwapParams | null };
