// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecuteResult } from "../ExecuteResult";
import type { TransactionId } from "../TransactionId";

export type TransactionSubmitManifestResponse = {
  transaction_id: TransactionId;
  required_fees: number | null;
  result: ExecuteResult | null;
};
