// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "../ResourceAddress";

/**
 * Net value movement for a stealth or confidential transfer, computed by the
 * wallet from the request's locks.
 *
 * A stealth transfer's instructions are commitments and range proofs, so a
 * human cannot read the amount out of them. The wallet owns the masks and is
 * the only party that can state what leaves the account.
 */
export type TransactionRequestValueSummary = {
  resource_address: ResourceAddress;
  /**
   * Total value of the inputs this request spends.
   */
  inputs_total: bigint;
  /**
   * Total value returning to this wallet as change.
   */
  change_total: bigint;
  /**
   * `inputs_total - change_total`: what actually leaves, before fees.
   */
  amount_leaving: bigint;
};
