// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectiveStatus } from "./EffectiveStatus";

export type TransactionRequestDecisionResponse = { request_id: number; status: EffectiveStatus };
