// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnsignedTransaction } from "../UnsignedTransaction";

/**
 * Resolve a transaction's inputs without submitting it.
 *
 * Detection returns the **dependency closure** of everything the instructions
 * reference (e.g. an account component pulls in every vault it holds), which
 * is a superset of what execution will touch: the wallet cannot know intent
 * without executing, so it over-approximates. Narrowing the set is the
 * caller's job — every declared input adds transaction weight (fees) and must
 * be locked by consensus, so the caller pays for anything left in.
 */
export type TransactionDetectInputsRequest = {
  transaction: UnsignedTransaction;
  /**
   * If true (default), detected inputs omit versions so consensus resolves
   * them; if false, walletd pins the versions it currently knows.
   */
  use_unversioned: boolean;
};
