// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionSignature } from "../TransactionSignature";
import type { UnsignedTransaction } from "../UnsignedTransaction";
import type { KeyId } from "./KeyId";

/**
 * Create a transaction request for a separately-permissioned principal to
 * approve (issue #2343).
 *
 * The transaction is stored verbatim and frozen: what the approver views is
 * what submit seals. The caller supplies a complete transaction (inputs
 * resolved, any out-of-band signatures collected); walletd does not alter it.
 */
export type TransactionRequestCreateRequest = {
  /**
   * The transaction, stored verbatim. Inputs must already be resolved: the
   * request path does not detect them, so that a caller who has already
   * collected signatures over these exact bytes is not invalidated. Use
   * `transactions.detect_inputs` first if the caller cannot resolve them.
   */
  transaction: UnsignedTransaction;
  /**
   * Who pays and seals last.
   */
  seal_signer: KeyId;
  /**
   * Wallet keys walletd signs with at submit.
   */
  other_signers: Array<KeyId>;
  /**
   * Signatures collected out of band (e.g. from an external co-signer) over
   * `transaction` and `seal_signer`'s public key. Attached verbatim at
   * submit. Their presence means the transaction is final, so nothing about
   * it is altered after creation.
   */
  signatures: Array<TransactionSignature>;
  /**
   * Locks holding this request's inputs. Their timeouts are extended to
   * outlive the approval window. Stealth spend keys are derived from these
   * at submit -- a caller cannot name them.
   */
  lock_ids: Array<number>;
  /**
   * How long a human has to approve, in seconds. Defaults to the daemon's
   * configured window.
   */
  ttl_secs: number | null;
};
