// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddress } from "../ComponentAddress";
import type { TransactionStatus } from "../TransactionStatus";

export type TransactionGetAllRequest = {
  status: TransactionStatus | null;
  /**
   * Filter to transactions involving this account. Transactions are linked to the account(s) they
   * involve at submission time, so this works even for stealth transactions.
   */
  account: ComponentAddress | null;
};
