// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { Memo } from "../Memo";
import type { OotleAddress } from "../OotleAddress";
import type { OutputStatus } from "../OutputStatus";
import type { SpendAuthorization } from "../SpendAuthorization";
import type { UtxoAddress } from "../UtxoAddress";

export type UtxoInfo = {
  address: UtxoAddress;
  value: Amount;
  status: OutputStatus;
  memo: Memo | null;
  /**
   * The sender's Ootle address, resolved from the memo when it is a `SenderAddress` variant, using the
   * wallet's configured network. `None` for all other memo types.
   */
  sender_address: OotleAddress | null;
  auth: SpendAuthorization;
  is_burnt: boolean;
  is_frozen: boolean;
  is_on_chain: boolean;
};
