// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "../Hash32";
import type { SubstateId } from "../SubstateId";

export type WalletSubstateInfo = { substate_id: SubstateId, parent_id: SubstateId | null, module_name: string | null, version: number, template_address: Hash32 | null, };
