// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebauthnFinishAuthRequest = { 
/**
 * Session ID received from [`WebauthnStartAuthResponse`].
 */
session_id: string, 
/**
 * [`PublicKeyCredential`]
 */
credential: object, };
