// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permission } from "../Permission";

export type WebauthnFinishRegisterRequest = { 
/**
 * Session ID received from [`WebauthnStartRegisterResponse`].
 */
session_id: string, 
/**
 * [`RegisterPublicKeyCredential`]
 */
credential: object, 
/**
 * Permissions requested by the client to be associated with the registered credential.
 */
requested_permissions: Array<Permission>, };
