// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebauthnStartAuthResponse = {
  /**
   * Session ID.
   */
  session_id: string;
  /**
   * [`RequestChallengeResponse`] serialized as JSON string.
   */
  challenge: object;
};
