// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "../Account";
import type { Amount } from "../Amount";
import type { FinalizeResult } from "../FinalizeResult";
import type { TransactionId } from "../TransactionId";

export interface AccountsCreateFreeTestCoinsResponse {
  account: Account;
  transaction_id: TransactionId;
  amount: Amount;
  fee: number;
  result: FinalizeResult;
  public_key: string;
}
