// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export type AccountsCreateOrGetRequest = {
  account: ComponentAddressOrName | null;
  is_default: boolean | null;
  key_id: number | null;
};
