// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebauthnFinishAuthRequest } from "./WebauthnFinishAuthRequest";

export interface AuthLoginRequest {
  permissions: Array<string>;
  duration: { secs: number; nanos: number } | null;
  webauthn_finish_auth_request: WebauthnFinishAuthRequest | null;
}
