// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionDef } from "../FunctionDef";
import type { Hash } from "../Hash";
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";

export interface AuthoredTemplate {
  author_public_key: RistrettoPublicKeyBytes;
  address: Hash;
  name: string;
  tari_version: string;
  functions: Array<FunctionDef>;
}
