// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyBranch } from "./KeyBranch";
import type { KeyId } from "./KeyId";

export type BranchAndKeyId = { branch: KeyBranch; key_id: KeyId };
