// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitmentSignatureBytes } from "../CommitmentSignatureBytes";
import type { PedersenCommitmentBytes } from "../PedersenCommitmentBytes";
import type { RangeProofBytes } from "../RangeProofBytes";
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";

export type ClaimBurnProof = {
  reciprocal_claim_public_key: RistrettoPublicKeyBytes;
  commitment: PedersenCommitmentBytes;
  ownership_proof: CommitmentSignatureBytes;
  range_proof: RangeProofBytes;
};
