// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddressOrName } from "./ComponentAddressOrName";
import type { ExtClaimBurnProof } from "./ExtClaimBurnProof";

export type ClaimBurnRequest = {
  account: ComponentAddressOrName;
  claim_proof: ExtClaimBurnProof;
  max_fee: number | null;
};
