// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaimBurnProof } from "./ClaimBurnProof";

export type ExtClaimBurnProof = { claim_proof: ClaimBurnProof; owner_nonce_key_index: number };
