// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShardGroup } from "../ShardGroup";
import type { AccountOrKeyIndex } from "./AccountOrKeyIndex";

export type GetValidatorFeesRequest = { account_or_key: AccountOrKeyIndex; shard_group: ShardGroup | null };
