// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeePoolDetails } from "./FeePoolDetails";
import type { Shard } from "../Shard";

export interface GetValidatorFeesResponse {
  fees: Record<Shard, FeePoolDetails>;
}
