// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyBranch = "account" | "transaction" | "view_key" | "stealth_masks" | "confidential_masks" | "nonce";
