// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyId = { Derived: { index: bigint } } | { Imported: { local_key_id: bigint } };
