// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeysListResponse = {
  /**
   * (index, public key, is_active)
   */
  keys: Array<[number, string, boolean]>;
};
