// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinalizeResult } from "../FinalizeResult";
import type { TransactionId } from "../TransactionId";

export interface MintFaucetNftResponse {
  transaction_id: TransactionId;
  finalize: FinalizeResult;
  fee: bigint;
}
