// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export interface MintFaucetNftRequest {
  account: ComponentAddressOrName;
  mutable_data: object;
  number_to_mint: bigint;
  max_fee: Amount | null;
}
