// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { ResourceAddress } from "../ResourceAddress";
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export type ProofsGenerateRequest = {
  amount: Amount;
  reveal_amount: Amount;
  account: ComponentAddressOrName | null;
  resource_address: ResourceAddress;
  destination_public_key: RistrettoPublicKeyBytes;
};
