// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export interface PublishTransactionRequest {
  binary: Array<number>;
  fee_account: ComponentAddressOrName;
  max_fee: number;
  detect_inputs: boolean;
}
