// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";

export interface PublishTemplateResponse {
  transaction_id: string;
  dry_run_fee: Amount | null;
}
