// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionId } from "../TransactionId";

export interface PublishTemplateResponse {
  transaction_id: TransactionId;
  dry_run_fee: number | null;
}
