// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PublishTemplateResponse {
  transaction_id: string;
  dry_run_fee: number | null;
}
