// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export interface PublishTemplateRequest {
  binary: string;
  fee_account: ComponentAddressOrName | null;
  max_fee: number;
  detect_inputs: boolean;
  dry_run: boolean;
}
