// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfidentialTransferInputSelection } from "../ConfidentialTransferInputSelection";
import type { ResourceAddress } from "../ResourceAddress";
import type { BadgeUsage } from "./BadgeUsage";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";
import type { StealthTransfer } from "./StealthTransfer";

export type StealthTransferRequest = {
  owner_account: ComponentAddressOrName;
  input_selection: ConfidentialTransferInputSelection;
  resource_address: ResourceAddress;
  badge_usage: BadgeUsage;
  transfers: Array<StealthTransfer>;
  max_fee: number;
  dry_run: boolean;
};
