// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TemplatesListAuthoredRequest {
  author_public_key: string;
  page: number;
  page_size: number;
}
