// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TemplatesListAuthoredRequest {
  key_index: number;
  page: number;
  page_size: number;
}
