// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export interface TransferNftRequest {
  nfts: Array<string>;
  fee_payer_account: ComponentAddressOrName;
  source_account: ComponentAddressOrName;
  target_account_public_key: string;
  max_fee: number;
  dry_run: boolean;
}
