// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransactionSubmitManifestRequest = {
  manifest: string;
  variables: { [key in string]?: string };
  signing_key_index: number | null;
  max_fee: number;
  dry_run: boolean;
};
