// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecuteResult } from "../ExecuteResult";
import type { TransactionId } from "../TransactionId";

export interface TransactionSubmitManifestResponse {
  transaction_id: TransactionId;
  result: ExecuteResult | null;
}
