// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";
import type { NonFungibleId } from "../NonFungibleId";

export interface TransferNftRequest {
  nft_ids: Array<NonFungibleId>;
  source_account: ComponentAddressOrName;
  target_account_public_key: string;
  max_fee: Amount;
  dry_run: boolean;
}
