// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyId } from "./KeyId";

export type TransactionSubmitManifestRequest = {
  manifest: string;
  variables: { [key in string]?: string };
  signing_key_id: KeyId | null;
  max_fee: number;
  dry_run: boolean;
};
