// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { Memo } from "../Memo";
import type { OotleAddress } from "../OotleAddress";

export type TransferOutput = {
  /**
   * Destination address used to derive the UTXO encryption keys, owner signature and the account in which to
   * deposit revealed funds
   */
  address: OotleAddress;
  /**
   * Amount to spend to a revealed output
   */
  revealed_amount: Amount;
  /**
   * Amount to spend to a blinded output
   */
  blinded_amount: Amount;
  /**
   * Optional memo to include a memo in the output. This memo is encrypted and can only be read by the recipient.
   */
  memo: Memo | null;
};
