// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinalizeResult } from "../FinalizeResult";
import type { TransactionStatus } from "../TransactionStatus";

export interface TransactionWaitResultResponse {
  transaction_id: string;
  result: FinalizeResult | null;
  status: TransactionStatus;
  final_fee: number;
  timed_out: boolean;
}
