// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnsignedTransaction } from "../UnsignedTransaction";

export type TransactionSubmitRequest = {
  transaction: UnsignedTransaction;
  signing_key_index: number | null;
  /**
   * Attempt to infer inputs and their dependencies from instructions. If false, the provided transaction must
   * contain the required inputs.
   */
  detect_inputs: boolean;
  /**
   * If true(default), detected inputs will omit versions allowing consensus to resolve input substates.
   * If false, the wallet will try determine versioned for the inputs. These may be outdated if the substate has
   * changed since detection.
   */
  detect_inputs_use_unversioned: boolean;
  proof_ids: Array<number>;
};
