// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WalletTransaction } from "../WalletTransaction";

export interface TransactionGetAllResponse {
  transactions: Array<WalletTransaction>;
}
