// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnsignedTransaction } from "../UnsignedTransaction";

export type TransactionSubmitDryRunRequest = {
  transaction: UnsignedTransaction;
  signing_key_index: number | null;
  detect_inputs: boolean;
  detect_inputs_use_unversioned: boolean;
  proof_ids: Array<number>;
};
