// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnsignedTransaction } from "../UnsignedTransaction";
import type { KeyId } from "./KeyId";

export type TransactionSubmitDryRunRequest = {
  transaction: UnsignedTransaction;
  signing_key_id: KeyId | null;
  detect_inputs: boolean;
  detect_inputs_use_unversioned: boolean;
  proof_ids: Array<number>;
};
