// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { OutputStatus } from "../OutputStatus";
import type { UtxoAddress } from "../UtxoAddress";

export type UtxoInfo = {
  address: UtxoAddress;
  value: Amount;
  status: OutputStatus;
  is_burnt: boolean;
  is_frozen: boolean;
  is_on_chain: boolean;
};
