// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebauthnStartRegisterResponse = {
  /**
   * Unique ID of the current registration Session.
   */
  session_id: string;
  /**
   * [`PublicKeyCredentialCreationOptions`] serialized as JSON
   */
  public_key: object;
};
