// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface WebauthnStartRegisterResponse { session_id: string, public_key: object, }