// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TemplateMetadata = {
  schema_version: number;
  name: string;
  version: string;
  description?: string;
  tags?: Array<string>;
  category?: string | null;
  repository?: string | null;
  documentation?: string | null;
  homepage?: string | null;
  license?: string | null;
  logo_url?: string | null;
  extra?: Record<string, string>;
};
