// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { Network } from "../Network";
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";

/**
 * The configuration of a single indexer node, as far as it affects what its API returns. Every field
 * is local to the node answering the request: two indexers on the same network can disagree on all of
 * them, so a client that cares must ask the node it is talking to.
 */
export type GetIndexerInfoResponse = {
  /**
   * The indexer's build version.
   */
  version: string;
  network: Network;
  network_byte: number;
  /**
   * The sidechain this indexer follows, if it is configured for one.
   */
  sidechain_id: RistrettoPublicKeyBytes | null;
  /**
   * The current epoch, so a client can resolve the epoch-denominated fields below against a clock
   * without a second request.
   */
  current_epoch: Epoch;
  /**
   * How many epochs past its terminal epoch this indexer retains a transaction submitted through it
   * before pruning the record. `None` means transactions are retained indefinitely. Transaction
   * receipts are retained regardless of this setting. A client paginating transaction history hits
   * this floor rather than the start of the chain.
   */
  transaction_retention_epochs: bigint | null;
  /**
   * Whether substates served by this indexer are verified against a shard group committee proof
   * before being returned. When false, values are served as fetched from a single validator and
   * carry no proof of correctness.
   */
  verify_substate_proofs: boolean;
  /**
   * How long this indexer may serve a cached substate as the latest version of that substate, in
   * seconds. A read of the latest version may be up to this stale; reads of a specific version are
   * unaffected.
   */
  latest_substate_cache_ttl_secs: bigint;
  /**
   * Whether this indexer stores every event on the network. When false it is configured with event
   * filters, so event queries answer over a subset and absence is not proof an event did not occur.
   */
  indexes_all_events: boolean;
};
