// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { Network } from "../Network";
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";

/**
 * The configuration of a single indexer node, as far as it affects what its API returns. Every field
 * is local to the node answering the request: two indexers on the same network can disagree on all of
 * them, so a client that cares must ask the node it is talking to.
 */
export type GetIndexerInfoResponse = {
  /**
   * The indexer's build version.
   */
  version: string;
  network: Network;
  network_byte: number;
  /**
   * The sidechain this indexer follows, if it is configured for one.
   */
  sidechain_id: RistrettoPublicKeyBytes | null;
  /**
   * The current epoch, so a client can resolve the epoch-denominated fields below against a clock
   * without a second request.
   */
  current_epoch: Epoch;
  /**
   * How many epochs past its terminal epoch this indexer retains a transaction before pruning the
   * record. `None` means transactions are retained indefinitely. A client paginating transaction
   * history hits this floor rather than the start of the chain.
   */
  transaction_retention_epochs: bigint | null;
  /**
   * How many epochs past the epoch its transaction committed in this indexer retains a transaction
   * receipt before pruning it. `None` means receipts are retained indefinitely. Longer than
   * `transaction_retention_epochs`, so a retained transaction always has its receipt.
   */
  transaction_receipt_retention_epochs: bigint | null;
  /**
   * How many epochs past the epoch its transaction committed in this indexer retains an event
   * before pruning it. `None` means events are retained indefinitely. Event queries and the event
   * stream's catch-up answer no further back than this.
   */
  event_retention_epochs: bigint | null;
  /**
   * Whether this indexer stores transactions observed on the network gossip topic in addition to
   * those submitted directly to it. When false, a transaction submitted elsewhere is unknown to
   * this indexer until its receipt is synced.
   *
   * Even when true the stored set of transactions is best effort: an indexer misses whatever was
   * gossiped while it was offline or while its inbound queue was full, and there is no backfill.
   * Transaction receipts carry no such caveat — they are synced from network state and are
   * complete back to `transaction_receipt_retention_epochs` — so a committed transaction always
   * has a receipt even when its body is missing here. Transactions that never committed get no receipt, so gossip is the only source
   * for them.
   */
  index_gossiped_transactions: boolean;
  /**
   * Whether substates served by this indexer are verified against a shard group committee proof
   * before being returned. When false, values are served as fetched from a single validator and
   * carry no proof of correctness.
   */
  verify_substate_proofs: boolean;
  /**
   * How long after a shard was last confirmed synced this indexer keeps serving cached substates
   * for it, in seconds. Cached values are invalidated by the state transitions this indexer syncs
   * rather than expired on a timer, so a served value trails the chain by the sync interval rather
   * than by this bound - which is what stops a validator that has stopped serving transitions from
   * holding a stale value open indefinitely.
   */
  substate_cache_max_serve_lag_secs: bigint;
  /**
   * Whether this indexer stores every event on the network. When false it is configured with event
   * filters, so event queries answer over a subset and absence is not proof an event did not occur.
   */
  indexes_all_events: boolean;
};
