// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { Network } from "../Network";

export type GetNetworkInfoResponse = { network: Network; network_byte: number; epoch: Epoch };
