// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkDescription } from "./NetworkDescription";
import type { SyncProgress } from "./SyncProgress";
import type { ValidatorStatus } from "./ValidatorStatus";

export type GetNetworkSyncStateResponse = {
  network_desc: NetworkDescription;
  sync_progress: SyncProgress | null;
  validators: Array<ValidatorStatus>;
};
