// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { Epoch } from "../Epoch";

export type GetNetworkEconomicsResponse = {
  current_epoch: Epoch;
  total_claimed: Amount;
  total_exhaust_burned: Amount;
  fee_volume: Amount;
  receipt_exhaust_burned: Amount;
  total_supply: Amount;
  transaction_receipt_count: bigint;
  target_burn_rate_bps: number;
};
