// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkDescription } from "./NetworkDescription";
import type { SyncProgress } from "./SyncProgress";
import type { ValidatorStatus } from "./ValidatorStatus";

export type GetNetworkSyncStateResponse = {
  network_desc: NetworkDescription;
  sync_progress: SyncProgress | null;
  /**
   * Per-validator consensus state as last observed by this indexer while
   * syncing from the network. Populated lazily, so validators that have
   * never been contacted for a sync will not appear here. Each entry
   * carries an `observed_at_unix_s` timestamp so callers can judge whether
   * the reading is fresh.
   */
  validators: Array<ValidatorStatus>;
};
