// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Substate } from "../Substate";
import type { SubstateId } from "../SubstateId";

export type GetSubstatesResponse = { substates: { [key in SubstateId]?: Substate } };
