// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash } from "../Hash";

export interface GetTemplateDefinitionRequest {
  template_address: Hash;
}
