// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UtxoUpdateSet } from "../UtxoUpdateSet";

export type GetUtxoUpdatesResponse = { updates: UtxoUpdateSet };
