// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "../ResourceAddress";
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";
import type { UtxoTag } from "../UtxoTag";

export type GetUnspentUtxosRequest = {
  tag_and_nonce_pairs: Array<[UtxoTag, RistrettoPublicKeyBytes]>;
  resource_address: ResourceAddress;
};
