// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UtxoUpdate } from "./UtxoUpdate";

export type GetUtxoUpdatesResponse = { utxo_updates: Array<UtxoUpdate> };
