// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { ResourceAddress } from "../ResourceAddress";
import type { Shard } from "../Shard";
import type { StateVersion } from "../StateVersion";

export type GetUtxoUpdatesRequest = {
  from_epoch: Epoch;
  shard_state_versions: Array<[Shard, StateVersion]>;
  resource_address: ResourceAddress;
  unspent_only?: boolean;
  per_shard_limit: number;
};
