// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionEnvelope } from "../TransactionEnvelope";

export type IndexerSubmitTransactionRequest = { transaction: TransactionEnvelope };
