// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { Hash32 } from "../Hash32";

export type IndexerGetEpochManagerStatsResponse = {
  current_epoch: Epoch;
  current_block_height: number;
  current_block_hash: Hash32;
};
