// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexerConnection } from "./IndexerConnection";

export type IndexerGetConnectionsResponse = { connections: Array<IndexerConnection> };
