// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionEntry } from "./TransactionEntry";

export type IndexerGetTransactionResponse = {
  /**
   * The stored transaction, including its instructions, fee instructions and signatures.
   */
  transaction: TransactionEntry;
};
