// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionEnvelope } from "../TransactionEnvelope";

export type IndexerSubmitTransactionRequest = {
  /**
   * A BOR-encoded transaction envelope, base64 encoded as a string
   */
  transaction: TransactionEnvelope;
};
