// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecuteResult } from "../ExecuteResult";
import type { TransactionId } from "../TransactionId";

export type IndexerSubmitTransactionResponse = {
  /**
   * The ID of the transaction that was dry-run
   */
  transaction_id: TransactionId;
  /**
   * The result of the dry-run execution, including any emitted events and state changes, but without a final
   * decision or commitment to the ledger
   */
  result: ExecuteResult;
};
