// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateValue } from "../SubstateValue";

export type IndexerGetSubstateResponse = { version: number; substate: SubstateValue };
