// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionId } from "../TransactionId";

export type IndexerSubmitTransactionResponse = {
  /**
   * The ID of the submitted transaction
   */
  transaction_id: TransactionId;
};
