// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";

export type IndexerGetIdentityResponse = {
  peer_id: string;
  public_key: RistrettoPublicKeyBytes;
  public_addresses: string[];
};
