// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";

export type IndexerAddPeerRequest = {
  public_key: RistrettoPublicKeyBytes;
  addresses: Array<string>;
  wait_for_dial: boolean;
};
