// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateId } from "../SubstateId";
import type { SubstateValue } from "../SubstateValue";

export type IndexerGetSubstateResponse = { address: SubstateId; version: number; substate: SubstateValue };
