// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexerTransactionFinalizedResult } from "./IndexerTransactionFinalizedResult";

export type IndexerGetTransactionResultResponse = {
  /**
   * The result of the transaction, which may be pending (not yet finalized) or finalized with details such as the
   * final decision, execution result, and timestamps
   */
  result: IndexerTransactionFinalizedResult;
};
