// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionEntry } from "./TransactionEntry";

export interface ListRecentTransactionsResponse {
  transactions: Array<TransactionEntry>;
}
