// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ordering } from "../Ordering";
import type { TransactionReceiptAddress } from "../TransactionReceiptAddress";

export type ListTransactionReceiptsRequest = {
  limit?: number | null;
  last_id?: TransactionReceiptAddress | null;
  ordering: Ordering;
};
