// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Utxo } from "../Utxo";
import type { UtxoId } from "../UtxoId";

export type ListUtxosResponse = { utxos: Array<[UtxoId, Utxo]> };
