// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchedTemplateItem } from "./WatchedTemplateItem";

export type ListWatchedTemplatesResponse = {
  templates: Array<WatchedTemplateItem>;
};
