// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "../Hash32";

export type ListWatchedSubstatesRequest = {
  template_address: Hash32 | null;
  limit: bigint | null;
  offset: bigint | null;
};
