// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";

export type ListValidatorsRequest = {
  /**
   * The epoch to fetch the roster for. Defaults to the current epoch.
   */
  epoch: Epoch | null;
};
