// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionReceipt } from "../TransactionReceipt";
import type { TransactionReceiptAddress } from "../TransactionReceiptAddress";

export type ListTransactionReceiptsResponse = { receipts: Array<[TransactionReceiptAddress, TransactionReceipt]> };
