// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";

export type ListEpochCheckpointsRequest = {
  /**
   * The epoch to start listing from (inclusive). Defaults to 0.
   */
  from_epoch: Epoch | null;
  /**
   * Maximum number of checkpoints to return (default: 20, max: 100).
   */
  limit: number | null;
};
