// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateCatalogueItem } from "./TemplateCatalogueItem";

export type ListTemplateCatalogueResponse = { entries: Array<TemplateCatalogueItem> };
