// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { ValidatorInfo } from "./ValidatorInfo";

/**
 * The validator roster for an epoch, as registered on the base layer and tracked by the epoch
 * manager. Unlike the lazily-observed snapshots in `GetNetworkSyncStateResponse`, this is the
 * complete consensus-derived validator set for the epoch.
 */
export type ListValidatorsResponse = {
  /**
   * The epoch the roster applies to.
   */
  epoch: Epoch;
  validators: Array<ValidatorInfo>;
};
