// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListTemplateCatalogueRequest = {
  /**
   * Optional substring filter on template name.
   */
  name_filter: string | null;
  /**
   * Maximum number of entries to return (default: 20, max: 100).
   */
  limit: bigint | null;
  /**
   * Cursor: return entries inserted after the row with this template address.
   * When omitted, returns from the beginning.
   */
  after: string | null;
};
