// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash } from "../Hash";
import type { SubstateId } from "../SubstateId";
import type { SubstateType } from "../SubstateType";

export type ListSubstatesRequest = {
  by_id: SubstateId | null;
  filter_by_template: Hash | null;
  filter_by_type: SubstateType | null;
  limit: bigint | null;
  offset: bigint | null;
};
