// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListTemplateCatalogueRequest = {
  /**
   * Optional substring filter on template name.
   */
  name_filter: string | null;
  /**
   * Only return templates published at or after this epoch. Use for incremental sync.
   */
  since_epoch: bigint | null;
  /**
   * Maximum number of entries to return (default: 20, max: 100).
   */
  limit: bigint | null;
  /**
   * Number of entries to skip for pagination.
   */
  offset: bigint | null;
};
