// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "../ResourceAddress";
import type { UtxoId } from "../UtxoId";

export type ListUtxosRequest = { resource_address: ResourceAddress; limit: number; from_id: UtxoId | null };
