// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { NumPreshards } from "../NumPreshards";
import type { ShardGroup } from "../ShardGroup";

export type NetworkDescription = {
  epoch: Epoch;
  shard_groups: Array<[ShardGroup, number]>;
  num_preshards: NumPreshards;
};
