// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonFungibleAddress } from "../NonFungibleAddress";
import type { SubstateValue } from "../SubstateValue";

export type NonFungibleSubstate = { address: NonFungibleAddress; version: number; substate: SubstateValue };
