// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateId } from "../SubstateId";

export type QueryTransactionEventsRequest = {
  /**
   * Filter events by topic
   */
  topic: string | null;
  substate_id: SubstateId | null;
  limit: number | null;
  offset: number | null;
};
