// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "../Event";
import type { TransactionId } from "../TransactionId";

export type QueryTransactionEventsResponse = { events: Array<[TransactionId, Event]> };
