// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "../Event";
import type { TransactionId } from "../TransactionId";

export type QueryTransactionEventsResponse = {
  events: Array<[TransactionId, Event]>;
  /**
   * The `before_id` for the next page, or `None` once no older event can match. A wildcard
   * topic query examines a bounded number of events per request, so a page can be short, or
   * empty, and still carry a cursor.
   */
  next_before_id?: bigint | null;
};
