// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "../ResourceAddress";
import type { SubstateId } from "../SubstateId";

export type QueryTransactionEventsRequest = {
  /**
   * Filter events by topic
   */
  topic: string | null;
  substate_id: SubstateId | null;
  /**
   * Filter by resource address. Matches when either the event's `substate_id` is the given
   * resource (std.resource.* events) or the event payload contains a `resource_address` entry
   * equal to the given address (std.vault.deposit / std.vault.withdraw).
   */
  resource_address?: ResourceAddress | null;
  limit: number | null;
  offset: number | null;
};
