// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "../ResourceAddress";
import type { SubstateId } from "../SubstateId";

export type QueryTransactionEventsRequest = {
  /**
   * Filter events by topic
   */
  topic: string | null;
  substate_id: SubstateId | null;
  /**
   * Filter by resource address. Matches the events whose `substate_id` is that resource, which
   * is the `std.resource.*` family. Vault events name no resource — filter those by
   * `substate_id`, the vault's ID.
   */
  resource_address?: ResourceAddress | null;
  limit: number | null;
  offset: number | null;
};
