// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "../Hash32";
import type { ResourceAddress } from "../ResourceAddress";
import type { SubstateId } from "../SubstateId";

/**
 * Filter parameters for the transaction events SSE stream.
 */
export type StreamTransactionEventsRequest = {
  topic: string | null;
  substate_id: SubstateId | null;
  template_address: Hash32 | null;
  /**
   * Filter by resource address. Matches the events whose `substate_id` is that resource, which
   * is the `std.resource.*` family. Vault events name no resource — filter those by
   * `substate_id`, the vault's ID.
   */
  resource_address?: ResourceAddress | null;
  /**
   * Resume the event stream from this event ID (exclusive). Events with id > after_id will be
   * replayed from the database before switching to the live stream.
   */
  after_id: number | bigint | string | null;
};
