// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "../Hash32";
import type { SubstateId } from "../SubstateId";

/**
 * Filter parameters for the transaction events SSE stream.
 */
export type StreamTransactionEventsRequest = {
  topic: string | null;
  substate_id: SubstateId | null;
  template_address: Hash32 | null;
  /**
   * Resume the event stream from this event ID (exclusive). Events with id > after_id will be
   * replayed from the database before switching to the live stream.
   */
  after_id: bigint | null;
};
