// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "../Hash32";
import type { ResourceAddress } from "../ResourceAddress";
import type { SubstateId } from "../SubstateId";

/**
 * Filter parameters for the transaction events SSE stream.
 */
export type StreamTransactionEventsRequest = {
  topic: string | null;
  substate_id: SubstateId | null;
  template_address: Hash32 | null;
  /**
   * Filter by resource address. Matches when either the event's `substate_id` is the given
   * resource (std.resource.* events) or the event payload contains a `resource_address` entry
   * equal to the given address (std.vault.deposit / std.vault.withdraw).
   */
  resource_address?: ResourceAddress | null;
  /**
   * Resume the event stream from this event ID (exclusive). Events with id > after_id will be
   * replayed from the database before switching to the live stream.
   */
  after_id: bigint | null;
};
