// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { Shard } from "../Shard";
import type { ShardGroup } from "../ShardGroup";
import type { StateVersion } from "../StateVersion";

export type SyncProgress = {
  last_epoch: Epoch;
  checkpoint_progress: Array<[ShardGroup, Epoch]>;
  last_state_versions: Array<[Shard, [StateVersion, Epoch]]>;
};
