// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { Hash32 } from "../Hash32";
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";

export type TemplateMetadata = {
  name: string;
  address: Hash32;
  binary_sha: Hash32;
  author_public_key: RistrettoPublicKeyBytes;
  code_size: number;
  epoch: Epoch;
};
