// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "../Hash32";
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";

export type TemplateCatalogueItem = {
  template_address: Hash32;
  template_name: string;
  author_public_key: RistrettoPublicKeyBytes;
  binary_hash: Hash32;
  at_epoch: bigint;
  metadata_hash?: string | null;
};
