// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transaction } from "../Transaction";
import type { TransactionId } from "../TransactionId";

export type TransactionEntry = { transaction_id: TransactionId; transaction: Transaction; created_at: string };
