// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinalizeOutcome } from "../FinalizeOutcome";

export type TransactionResultSummary = {
  outcome: FinalizeOutcome;
  total_fees_paid: bigint;
  finalized_at: string;
};
