// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrunedTransaction } from "../PrunedTransaction";
import type { TransactionId } from "../TransactionId";

export type TransactionEntry = {
  transaction_id: TransactionId;
  /**
   * Pruned transaction — blob commitments retained, raw blob bytes omitted.
   */
  transaction: PrunedTransaction;
  created_at: string;
};
