// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shard } from "../Shard";
import type { StateVersion } from "../StateVersion";
import type { Utxo } from "../Utxo";
import type { VersionedSubstateId } from "../VersionedSubstateId";

export type UtxoUnspent = {
  versioned_substate_id: VersionedSubstateId;
  shard: Shard;
  state_version: StateVersion;
  utxo: Utxo;
};
