// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UtxoSpent } from "./UtxoSpent";
import type { UtxoUnspent } from "./UtxoUnspent";

export type UtxoUpdate = { Unspent: UtxoUnspent } | { Spent: UtxoSpent };
