// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StateVersion } from "../StateVersion";
import type { VersionedSubstateId } from "../VersionedSubstateId";

export type UtxoSpent = { versioned_substate_id: VersionedSubstateId; state_version: StateVersion };
