// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { RistrettoPublicKeyBytes } from "../RistrettoPublicKeyBytes";
import type { ShardGroup } from "../ShardGroup";

/**
 * A single validator's registration entry for an epoch.
 */
export type ValidatorInfo = {
  /**
   * The validator's consensus public key.
   */
  public_key: RistrettoPublicKeyBytes;
  /**
   * libp2p PeerId derived from the public key. Can be used to join against the liveness
   * snapshots in `GetNetworkSyncStateResponse.validators`.
   */
  peer_id: string;
  /**
   * The committee (shard group) the validator belongs to in this epoch.
   */
  shard_group: ShardGroup;
  /**
   * The first epoch the validator's registration is active.
   */
  start_epoch: Epoch;
  /**
   * The epoch the validator was deactivated, if any.
   */
  end_epoch: Epoch | null;
  /**
   * The public key that may claim fees earned by this validator.
   */
  fee_claim_public_key: RistrettoPublicKeyBytes;
  vote_power: bigint;
};
