// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";
import type { ShardGroup } from "../ShardGroup";
import type { ValidatorConsensusState } from "./ValidatorConsensusState";

export type ValidatorStatus = {
  peer_id: string;
  shard_group: ShardGroup;
  epoch: Epoch;
  height: number;
  state: ValidatorConsensusState;
  observed_at_unix_s: number;
  age_seconds: number;
};
