// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ValidatorConsensusState = "Idle" | "CheckSync" | "Syncing" | "Running" | "OnHold" | "Sleeping" | "Shutdown";
