// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hash32 } from "../Hash32";
import type { SubstateId } from "../SubstateId";

export type WatchedSubstateItem = { component_address: SubstateId; template_address: Hash32 };
