---
name: Security audit

'on':
  # push:
  #   paths:
  #     # Run if workflow changes
  #     - '.github/workflows/audit.yml'
  #     # Run on changed dependencies
  #     - '**/Cargo.toml'
  #     - '**/Cargo.lock'
  #     # Run if the configuration file changes
  #     - '**/audit.toml'
  # Rerun periodicly to pick up new advisories
  schedule:
    - cron: '43 05 * * *'
  # Run manually
  workflow_dispatch:

permissions: {}

jobs:
  security_audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
