name: Deploy Docs to Cloudflare

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: docs/developer-docs/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: docs/developer-docs

      - name: Build
        run: npm run build
        working-directory: docs/developer-docs

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@9acf94ace14e7dc412b076f2c5c20b8ce93c79cd # v3.15.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: docs/developer-docs
          command: deploy dist --project-name=tari-ootle-docs
